// AUTO-GENERATED by prototypes/jot-forms/mls-input/scripts/codegen.mjs — do not edit manually

export type ConditionWhen = {
  field?: string;
  equals?: string;
  includes?: string;
  all?: Array<{ field: string; equals?: string; includes?: string }>;
};

export type ConditionRule = {
  id: string;
  description?: string;
  when?: ConditionWhen;
  all?: Array<{ field: string; equals?: string; includes?: string }>;
  show?: string[];
  dynamic?: {
    field: string;
    rowCountFrom: string;
    rowLabels: string[];
  };
};

export const MLS_CONDITION_RULES: ConditionRule[] = [
  {
    "id": "secondary-owner-contact",
    "description": "Show secondary owner contact fields when two owners are listed.",
    "when": {
      "field": "ownerCount",
      "equals": "Two"
    },
    "show": [
      "secondaryOwnerName",
      "secondaryOwnerPhone",
      "secondaryOwnerEmail"
    ]
  },
  {
    "id": "secondary-owner-signature",
    "description": "Show secondary owner signature when two owners are listed.",
    "when": {
      "field": "ownerCount",
      "equals": "Two"
    },
    "show": [
      "q23-signature23"
    ]
  },
  {
    "id": "non-standard-address-directions",
    "description": "Show directions when address is non-standard.",
    "when": {
      "field": "nonStandardAddress",
      "equals": "Yes"
    },
    "show": [
      "directionsRemarks"
    ]
  },
  {
    "id": "owner-address-fields",
    "description": "Show owner mailing address when it differs from the listing address.",
    "when": {
      "field": "ownerAddressSameAsListing",
      "equals": "No"
    },
    "show": [
      "ownerAddress"
    ]
  },
  {
    "id": "hoa-fee-and-contact",
    "description": "Show HOA fee and contact when property is in an HOA.",
    "when": {
      "field": "hoa",
      "equals": "Yes"
    },
    "show": [
      "hoaFeeMonth",
      "hoaContact",
      "hoaContactPhone",
      "hoaRemarks"
    ]
  },
  {
    "id": "level-matrix-rows",
    "description": "Level breakdown matrix row count follows the selected number of levels.",
    "dynamic": {
      "field": "q117-2level117",
      "rowCountFrom": "levelCount",
      "rowLabels": [
        "Main Level",
        "Basement",
        "Second Story",
        "Third Story",
        "Fourth Story"
      ]
    }
  },
  {
    "id": "garage-capacity",
    "description": "Show garage capacity when Parking includes Garage.",
    "when": {
      "field": "q30-typea30",
      "includes": "Garage"
    },
    "show": [
      "q208-garagecapacity"
    ]
  },
  {
    "id": "carport-capacity",
    "description": "Show carport capacity when Parking includes Carport.",
    "when": {
      "field": "q30-typea30",
      "includes": "Carport"
    },
    "show": [
      "q209-garagecapacity209"
    ]
  },
  {
    "id": "pool-features",
    "description": "Show pool type/features when property has a pool.",
    "when": {
      "field": "q184-doesthe",
      "equals": "Yes"
    },
    "show": [
      "q63-pooltype"
    ]
  },
  {
    "id": "owner-occupied-showings",
    "description": "Owner-occupied showing approval flow.",
    "when": {
      "field": "q191-propertyoccupancy",
      "equals": "Owner Occupied"
    },
    "show": [
      "q192-howmany",
      "q194-ownershowing",
      "q195-phonenumber",
      "q196-email",
      "q197-ownershowing197",
      "q198-ownershowing198",
      "q199-ownershowing199"
    ]
  },
  {
    "id": "owner-showing-contact-2",
    "description": "Second owner showing contact when two owners can approve.",
    "when": {
      "all": [
        {
          "field": "q191-propertyoccupancy",
          "equals": "Owner Occupied"
        },
        {
          "field": "q192-howmany",
          "equals": "Two"
        }
      ]
    },
    "show": [
      "q197-ownershowing197",
      "q198-ownershowing198",
      "q199-ownershowing199"
    ]
  },
  {
    "id": "tenant-occupied-showings",
    "description": "Tenant-occupied showing approval flow.",
    "when": {
      "field": "q191-propertyoccupancy",
      "equals": "Tenant Occupied"
    },
    "show": [
      "q193-howmany193",
      "q200-tenantshowing",
      "q201-ownershowing201",
      "q202-tenantshowing202",
      "q203-tenantshowing203",
      "q204-tenantshowing204",
      "q205-tenantshowing205"
    ]
  },
  {
    "id": "tenant-showing-contact-2",
    "description": "Second tenant showing contact when two tenants can approve.",
    "when": {
      "all": [
        {
          "field": "q191-propertyoccupancy",
          "equals": "Tenant Occupied"
        },
        {
          "field": "q193-howmany193",
          "equals": "Two"
        }
      ]
    },
    "show": [
      "q203-tenantshowing203",
      "q204-tenantshowing204",
      "q205-tenantshowing205"
    ]
  },
  {
    "id": "alternate-title-company",
    "description": "Alternate title company contact when seller declines Prime Title.",
    "when": {
      "field": "q207-typea207",
      "equals": "No, I have someone else"
    },
    "show": [
      "q211-name211",
      "q212-typea212",
      "q213-email213",
      "q214-phonenumber214"
    ]
  }
];

const HIDDEN_BY_DEFAULT = new Set<string>(["secondaryOwnerName","secondaryOwnerPhone","secondaryOwnerEmail","listingQuadrant","directionsRemarks","ownerAddress","hoaFeeMonth","hoaContact","hoaContactPhone","q208-garagecapacity","q209-garagecapacity209","q63-pooltype","q192-howmany","q193-howmany193","q194-ownershowing","q195-phonenumber","q196-email","q197-ownershowing197","q198-ownershowing198","q199-ownershowing199","q200-tenantshowing","q201-ownershowing201","q202-tenantshowing202","q203-tenantshowing203","q204-tenantshowing204","q205-tenantshowing205","q211-name211","q212-typea212","q213-email213","q214-phonenumber214","hoaRemarks","q23-signature23"]);

function getFieldValue(values: Record<string, unknown>, fieldId: string): unknown {
  return values[fieldId];
}

function matchesCondition(
  cond: { field: string; equals?: string; includes?: string },
  values: Record<string, unknown>,
): boolean {
  const val = getFieldValue(values, cond.field);
  if (cond.equals !== undefined) return val === cond.equals;
  if (cond.includes !== undefined) {
    if (Array.isArray(val)) return val.includes(cond.includes);
    return false;
  }
  return false;
}

function matchesWhen(when: ConditionWhen, values: Record<string, unknown>): boolean {
  if (when.all?.length) {
    return when.all.every((c) => matchesCondition(c, values));
  }
  if (when.field) {
    return matchesCondition(
      { field: when.field, equals: when.equals, includes: when.includes },
      values,
    );
  }
  return false;
}

function ruleMatches(rule: ConditionRule, values: Record<string, unknown>): boolean {
  if (rule.when) return matchesWhen(rule.when, values);
  if (rule.all) return rule.all.every((c) => matchesCondition(c, values));
  return false;
}

const shownByRules = new Map<string, Set<string>>();

for (const rule of MLS_CONDITION_RULES) {
  if (!rule.show) continue;
  const key = JSON.stringify(rule.when ?? rule.all ?? {});
  if (!shownByRules.has(key)) shownByRules.set(key, new Set());
  for (const id of rule.show) shownByRules.get(key)!.add(id);
}

export function isFieldVisible(fieldId: string, values: Record<string, unknown>): boolean {
  if (!HIDDEN_BY_DEFAULT.has(fieldId)) return true;

  for (const rule of MLS_CONDITION_RULES) {
    if (!rule.show?.includes(fieldId)) continue;
    if (ruleMatches(rule, values)) return true;
  }
  return false;
}

export function getMatrixRowCount(
  matrixFieldId: string,
  values: Record<string, unknown>,
): number {
  const rule = MLS_CONDITION_RULES.find((r) => r.dynamic?.field === matrixFieldId);
  if (!rule?.dynamic) return 1;

  const countVal = getFieldValue(values, rule.dynamic.rowCountFrom);
  const labels = rule.dynamic.rowLabels ?? [];
  if (typeof countVal === "string") {
    const map: Record<string, number> = {
      One: 1,
      Two: 2,
      Three: 3,
      Four: 4,
      Five: 5,
      "1": 1,
      "2": 2,
      "3": 3,
      "4": 4,
      "5": 5,
    };
    if (map[countVal] !== undefined) return Math.min(map[countVal], labels.length);
    const parsed = parseInt(countVal, 10);
    if (!Number.isNaN(parsed)) return Math.min(parsed, labels.length);
  }
  if (typeof countVal === "number") return Math.min(countVal, labels.length);
  return 1;
}

export function getMatrixRowLabels(
  matrixFieldId: string,
  values: Record<string, unknown>,
): string[] {
  const rule = MLS_CONDITION_RULES.find((r) => r.dynamic?.field === matrixFieldId);
  const labels = rule?.dynamic?.rowLabels ?? [];
  const count = getMatrixRowCount(matrixFieldId, values);
  return labels.slice(0, count);
}
