// AUTO-GENERATED by prototypes/jot-forms/mls-input/scripts/codegen.mjs — do not edit manually

export type MlsInputFieldType =
  | "text"
  | "textarea"
  | "radio"
  | "checkbox"
  | "select"
  | "number"
  | "currency"
  | "email"
  | "phone"
  | "fullname"
  | "address"
  | "matrix"
  | "file"
  | "signature"
  | "content";

export type MlsInputMatrixColumn = {
  id: string;
  label: string;
  type: string;
  options?: string[];
};

export type MlsInputField = {
  id: string;
  label?: string;
  type: MlsInputFieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  description?: string;
  content?: string;
  status?: string;
  rows?: string[];
  columns?: MlsInputMatrixColumn[];
  dynamic?: {
    rowCountFrom?: string;
    rowLabels?: string[];
  };
  otherText?: boolean;
  multiple?: boolean;
  min?: number;
  max?: number;
  default?: number;
};

export type MlsInputStep = {
  order: number;
  id: string;
  title: string;
  intro?: string | null;
  fields: MlsInputField[];
};

export type MlsInputFormValues = {
  "ownerCount"?: string;
  "primaryOwnerName"?: { first: string; last: string };
  "primaryOwnerPhone"?: string;
  "primaryOwnerEmail"?: string;
  "secondaryOwnerName"?: { first: string; last: string };
  "secondaryOwnerPhone"?: string;
  "secondaryOwnerEmail"?: string;
  "specialOwnerType"?: string[];
  "listingAddress"?: { street: string; city: string; state: string; zip: string };
  "houseNumberDirection"?: string;
  "streetDirection"?: string;
  "listingCounty"?: string;
  "listingQuadrant"?: string;
  "coordNorthSouth"?: string;
  "coordEastWest"?: string;
  "projectSubdivision"?: string;
  "nonStandardAddress"?: string;
  "directionsRemarks"?: string;
  "ownerAddressSameAsListing"?: string;
  "ownerAddress"?: { street: string; city: string; state: string; zip: string };
  "listingPrice"?: string;
  "listingEffectiveDate"?: string;
  "listingExpirationDate"?: string;
  "listingType"?: string;
  "specialListingConditions"?: string[];
  "possession"?: string;
  "contactType"?: string;
  "appointmentContact"?: string;
  "contactPhone1"?: string;
  "contactPhone2"?: string;
  "listingAgentName"?: string;
  "listingCoAgentName"?: string;
  "listingOfficeName"?: string;
  "schools"?: Record<string, Record<string, string | string[]>>;
  "otherSchool"?: string;
  "hoa"?: string;
  "hoaFeeMonth"?: string;
  "hoaFeeFrequency"?: string;
  "hoaChangeFeeType"?: string;
  "hoaChangeFeeAmount"?: string;
  "hoaContact"?: string;
  "hoaContactPhone"?: string;
  "hoaRentalCap"?: string;
  "hoaAmenities"?: string[];
  "hoaRemarks"?: string;
  "shortTermRentals"?: string;
  "projectRestriction"?: string;
  "seniorCommunity"?: string;
  "maintenanceFree"?: string;
  "solar"?: string;
  "solarOwnership"?: string;
  "solarYearInstalled"?: string;
  "solarSystemSizeKw"?: string;
  "solarBatteryStorage"?: string;
  "solarLoanOrLien"?: string;
  "solarDocsAvailable"?: string;
  "solarCompanyName"?: string;
  "solarFinanceCompany"?: string;
  "solarMonthlyPayment"?: string;
  "solarAgreementTerm"?: string;
  "solarTransferable"?: string;
  "q11-propertytype"?: string;
  "pud"?: string;
  "pid"?: string;
  "constructionStatus"?: string;
  "q51-styleof51"?: string;
  "yearBuilt"?: string;
  "effectiveYearBuilt"?: string;
  "noAssignedParcelNumber"?: string;
  "taxParcelNumber"?: string;
  "estimatedTaxes"?: string;
  "waterShares"?: string;
  "lotSize"?: string;
  "lotFrontage"?: string;
  "lotSide"?: string;
  "lotBack"?: string;
  "lotIrregularShape"?: string;
  "frontageFacing"?: string;
  "livingSqft"?: string;
  "adu"?: string;
  "aduType"?: string;
  "aduSqft"?: string;
  "aduBeds"?: string;
  "aduBaths"?: string;
  "aduKitchen"?: string;
  "aduSeparateEntrance"?: string;
  "aduSeparateWaterMeter"?: string;
  "aduSeparateGasMeter"?: string;
  "aduSeparateElectricMeter"?: string;
  "aduCurrentlyRented"?: string;
  "aduMonthlyRent"?: string;
  "aduRemarks"?: string;
  "levelCount"?: string;
  "q26-typea26"?: string[];
  "basementFinished"?: string;
  "q117-2level117"?: Record<string, Record<string, string | string[]>>;
  "q33-flooring"?: string[];
  "q34-typea34"?: string[];
  "q27-typea27"?: string[];
  "q41-window-coverings"?: string[];
  "q42-amenities"?: string[];
  "q31-airconditioning"?: string[];
  "q96-hvac96"?: string[];
  "q32-typea32"?: string[];
  "q29-typea29"?: string[];
  "deckCount"?: string;
  "patioCount"?: string;
  "q30-typea30"?: string[];
  "q208-garagecapacity"?: string;
  "q209-garagecapacity209"?: string;
  "parkingCapacity"?: string;
  "rvParkingHeight"?: string;
  "rvParkingLength"?: string;
  "q28-typea28"?: string[];
  "q184-doesthe"?: string;
  "q63-pooltype"?: string[];
  "spaAvailable"?: string;
  "communityPool"?: string;
  "q37-typea37"?: string[];
  "q36-typea36"?: string[];
  "q43-lot-facts"?: string[];
  "petsAllowed"?: string;
  "q47-animals"?: string[];
  "q39-typea39"?: string[];
  "q35-connectedutilities"?: string[];
  "q44-water"?: string[];
  "q45-telecommunications"?: string[];
  "q46-environmental-certs"?: string[];
  "q38-zoning"?: string[];
  "q40-typea40"?: string[];
  "q19-typea19"?: Record<string, Record<string, string | string[]>>;
  "q191-propertyoccupancy"?: string;
  "q192-howmany"?: string;
  "q193-howmany193"?: string;
  "q194-ownershowing"?: { first: string; last: string };
  "q195-phonenumber"?: string;
  "q196-email"?: string;
  "q197-ownershowing197"?: { first: string; last: string };
  "q198-ownershowing198"?: string;
  "q199-ownershowing199"?: string;
  "q200-tenantshowing"?: { first: string; last: string };
  "q201-ownershowing201"?: string;
  "q202-tenantshowing202"?: string;
  "q203-tenantshowing203"?: { first: string; last: string };
  "q204-tenantshowing204"?: string;
  "q205-tenantshowing205"?: string;
  "q100-showinginstructions"?: string;
  "showInstructions"?: string[];
  "q207-typea207"?: string;
  "q211-name211"?: { first: string; last: string };
  "q212-typea212"?: string;
  "q213-email213"?: string;
  "q214-phonenumber214"?: string;
  "q97-publicremarks"?: string;
  "exclusionsRemarks"?: string;
  "q98-commentsto"?: string;
  "field-44"?: Array<{ name: string; url: string }>;
  "q20-signature"?: string;
  "q20-initials"?: string;
  "q23-signature23"?: string;
  "q23-initials"?: string;
  inquiryId?: string;
  photos?: Array<{ name: string; url: string }>;
};

export const MLS_INPUT_STEPS: MlsInputStep[] = [
  {
    "order": 1,
    "id": "owners",
    "title": "Owners",
    "intro": null,
    "fields": [
      {
        "id": "ownersIntro",
        "type": "content",
        "content": "If there are more than 2 owners or you need to sign for an entity (LLC, Partnership etc), Please select 1 owner and reply to the email you receive when this information is submitted.\n\nOnce this form is complete and we have your email, we can then send the form to the other parties for their signature and/or will collect the operating agreements etc. verifying proof of ownership and/or the right to sign as an officer for the entity prior to placing the property on the MLS.\n"
      },
      {
        "id": "ownerCount",
        "label": "How Many Owners Of The Property?",
        "type": "radio",
        "required": true,
        "options": [
          "One",
          "Two"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 2,
    "id": "primary-owner",
    "title": "Primary Owner",
    "intro": null,
    "fields": [
      {
        "id": "primaryOwnerName",
        "label": "Primary Owner Name",
        "type": "fullname",
        "required": true
      },
      {
        "id": "primaryOwnerPhone",
        "label": "Primary Owner Phone Number",
        "type": "phone",
        "required": true,
        "placeholder": "(000) 000-0000"
      },
      {
        "id": "primaryOwnerEmail",
        "label": "Primary Owner Email",
        "type": "email",
        "required": true,
        "placeholder": "example@example.com"
      },
      {
        "id": "secondaryOwnerName",
        "label": "Secondary Owner Name",
        "type": "fullname",
        "required": true,
        "status": "hidden-in-jotform"
      },
      {
        "id": "secondaryOwnerPhone",
        "label": "Secondary Owner Phone Number",
        "type": "phone",
        "required": true,
        "placeholder": "(000) 000-0000",
        "status": "hidden-in-jotform"
      },
      {
        "id": "secondaryOwnerEmail",
        "label": "Secondary Owner Email",
        "type": "email",
        "required": true,
        "placeholder": "example@example.com",
        "status": "hidden-in-jotform"
      },
      {
        "id": "specialOwnerType",
        "label": "Special Owner Type",
        "type": "checkbox",
        "required": false,
        "description": "Select any that apply, or leave blank if none.",
        "options": [
          "REO/Bank Owned",
          "HUD Owned",
          "Agent Owned",
          "Fractional Ownership",
          "LLC",
          "Trust"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 3,
    "id": "listing-address-schools",
    "title": "Listing Address & Schools",
    "intro": null,
    "fields": [
      {
        "id": "listingAddress",
        "label": "Listing Address",
        "type": "address",
        "required": true,
        "description": "Street address of the property being listed."
      },
      {
        "id": "houseNumberDirection",
        "label": "House Number Direction",
        "type": "radio",
        "description": "Optional N / S / E / W for the house number (Utah grid). Leave blank if unknown — agent/VA can fill later.",
        "options": [
          "N",
          "S",
          "E",
          "W"
        ],
        "otherText": false
      },
      {
        "id": "streetDirection",
        "label": "Street Name Direction",
        "type": "radio",
        "description": "Optional N / S / E / W for the street name or number. Leave blank if unknown — agent/VA can fill later.",
        "options": [
          "N",
          "S",
          "E",
          "W"
        ],
        "otherText": false
      },
      {
        "id": "listingCounty",
        "label": "County",
        "type": "text",
        "required": true,
        "placeholder": "e.g., Salt Lake"
      },
      {
        "id": "listingQuadrant",
        "label": "Quadrant",
        "type": "radio",
        "status": "hidden-in-jotform",
        "description": "NW, NE, SW, or SE area of the city (WFRMLS requirement).",
        "options": [
          "NW",
          "NE",
          "SW",
          "SE"
        ],
        "otherText": false
      },
      {
        "id": "coordNorthSouth",
        "label": "North / South Coordinate",
        "type": "number",
        "placeholder": "e.g., 2100",
        "description": "Utah grid north–south address number (optional). Agent/VA can fill if blank."
      },
      {
        "id": "coordEastWest",
        "label": "East / West Coordinate",
        "type": "number",
        "placeholder": "e.g., 1300",
        "description": "Utah grid east–west address number (optional). Agent/VA can fill if blank."
      },
      {
        "id": "projectSubdivision",
        "label": "Project / Subdivision",
        "type": "text",
        "placeholder": "e.g., Daybreak, Forest Dale",
        "description": "Name of the project or subdivision, if applicable."
      },
      {
        "id": "nonStandardAddress",
        "label": "Is this a non-standard address?",
        "type": "radio",
        "required": true,
        "description": "Choose Yes if the property is hard to find from the street address alone (for example rural, gated, or no formal street address). You will be asked for directions.",
        "options": [
          "No",
          "Yes"
        ],
        "otherText": false
      },
      {
        "id": "directionsRemarks",
        "label": "Directions / Non-Standard Address",
        "type": "textarea",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "Describe how to find the property if the address alone is not sufficient."
      },
      {
        "id": "ownerAddressSameAsListing",
        "label": "Is the OWNER address the SAME as the LISTING address?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "ownerAddress",
        "label": "Owner Address",
        "type": "address",
        "required": true,
        "status": "hidden-in-jotform"
      },
      {
        "id": "listingPrice",
        "label": "Listing Price",
        "type": "currency",
        "required": true,
        "placeholder": "e.g., $500,000"
      },
      {
        "id": "listingEffectiveDate",
        "label": "Effective Date of Listing Agreement",
        "type": "text",
        "placeholder": "MM/DD/YYYY",
        "description": "Optional — VA/agent can fill when the listing agreement is signed."
      },
      {
        "id": "listingExpirationDate",
        "label": "Expiration Date",
        "type": "text",
        "placeholder": "MM/DD/YYYY",
        "description": "Optional — VA/agent can fill when the listing agreement is signed."
      },
      {
        "id": "listingType",
        "label": "Listing Type",
        "type": "radio",
        "description": "Optional — defaults to Exclusive Right to Sell (ERS) if left blank.",
        "options": [
          "Exclusive Right to Sell (ERS)",
          "Exclusive Agency (EAL)"
        ],
        "otherText": false
      },
      {
        "id": "specialListingConditions",
        "label": "Special Listing Conditions",
        "type": "checkbox",
        "required": false,
        "description": "Select any that apply, or leave blank if none.",
        "options": [
          "Short Sale",
          "In Foreclosure",
          "In Probate",
          "Bankruptcy",
          "Notice of Default",
          "Trustee Sale",
          "Price Was Approved by Third Party",
          "Third Party Approval Required",
          "Offer Under Third Party Review",
          "Auction"
        ],
        "otherText": false
      },
      {
        "id": "possession",
        "label": "Possession",
        "type": "text",
        "placeholder": "e.g., Upon Closing, Immediate, Negotiable",
        "description": "When the buyer may take possession (optional)."
      },
      {
        "id": "contactType",
        "label": "Contact Type",
        "type": "radio",
        "description": "Who to contact for appointments and access (optional).",
        "options": [
          "Agent",
          "Owner",
          "Assistant"
        ],
        "otherText": false
      },
      {
        "id": "appointmentContact",
        "label": "Contact for Appointments & Access",
        "type": "text",
        "placeholder": "Name of contact person"
      },
      {
        "id": "contactPhone1",
        "label": "Contact Phone 1",
        "type": "phone",
        "placeholder": "(000) 000-0000"
      },
      {
        "id": "contactPhone2",
        "label": "Contact Phone 2",
        "type": "phone",
        "placeholder": "(000) 000-0000"
      },
      {
        "id": "listingAgentName",
        "label": "Listing Agent",
        "type": "text",
        "placeholder": "Agent name",
        "description": "Optional — VA/agent can fill."
      },
      {
        "id": "listingCoAgentName",
        "label": "Co-Agent",
        "type": "text",
        "placeholder": "Co-agent name, if any",
        "description": "Optional — VA/agent can fill."
      },
      {
        "id": "listingOfficeName",
        "label": "Office Name",
        "type": "text",
        "placeholder": "Listing office / brokerage",
        "description": "Optional — VA/agent can fill."
      },
      {
        "id": "schools",
        "label": "Schools",
        "type": "matrix",
        "required": true,
        "rows": [
          "School District",
          "Elementary School",
          "Junior High/Middle School",
          "High School"
        ],
        "columns": [
          {
            "id": "name",
            "label": "NAME",
            "type": "text"
          }
        ]
      },
      {
        "id": "otherSchool",
        "label": "Other School",
        "type": "text",
        "placeholder": "If applicable",
        "description": "Optional — any other school not listed above."
      }
    ]
  },
  {
    "order": 4,
    "id": "hoa-solar",
    "title": "HOA & Solar",
    "intro": null,
    "fields": [
      {
        "id": "hoa",
        "label": "Is the property in an HOA?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "hoaFeeMonth",
        "label": "HOA Fee Amount",
        "type": "currency",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "e.g., $150"
      },
      {
        "id": "hoaFeeFrequency",
        "label": "HOA Fee Frequency",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Monthly",
          "Quarterly",
          "Annually"
        ],
        "otherText": false
      },
      {
        "id": "hoaChangeFeeType",
        "label": "HOA Change / Transfer Fee",
        "type": "radio",
        "status": "hidden-in-jotform",
        "description": "How any HOA change or transfer fee is calculated, if applicable.",
        "options": [
          "Percentage of sales price",
          "Dollar amount",
          "None / Unknown"
        ],
        "otherText": false
      },
      {
        "id": "hoaChangeFeeAmount",
        "label": "HOA Change Fee Amount",
        "type": "text",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 0.5% or $500",
        "description": "Enter the percentage or dollar amount of the change/transfer fee."
      },
      {
        "id": "hoaContact",
        "label": "HOA Contact Name",
        "type": "text",
        "status": "hidden-in-jotform"
      },
      {
        "id": "hoaContactPhone",
        "label": "HOA Contact Phone",
        "type": "phone",
        "status": "hidden-in-jotform"
      },
      {
        "id": "hoaRentalCap",
        "label": "Does the HOA have a rental cap?",
        "type": "radio",
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "hoaAmenities",
        "label": "HOA Amenities",
        "type": "checkbox",
        "status": "hidden-in-jotform",
        "description": "Community / HOA amenities (not individual property features).",
        "options": [
          "None",
          "Alarm System Paid",
          "Barbecue",
          "Biking Trails",
          "Bocce Ball Court",
          "Cable TV Paid",
          "Club House",
          "Common RV Parking",
          "Concierge",
          "Controlled Access",
          "Earthquake Insurance",
          "Electricity Paid",
          "Fire Pit",
          "Gas Paid",
          "Gated",
          "Golf Course",
          "Gym Room",
          "Hiking Trails",
          "Horse Trails",
          "Insurance Paid",
          "Internet Paid",
          "Maintenance Paid",
          "On Site Security",
          "On site Property Mgmt",
          "Pet Rules",
          "Pets Not Permitted",
          "Pets Permitted",
          "Pickleball Court",
          "Picnic Area",
          "Playground",
          "Pool",
          "Racquet Ball Court",
          "Sauna",
          "Security",
          "Sewer Paid",
          "Snow Removal",
          "Spa",
          "Storage Area",
          "Tennis Court",
          "Trash Paid",
          "Water Paid",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "hoaRemarks",
        "type": "textarea",
        "label": "HOA Remarks",
        "status": "hidden-in-jotform",
        "placeholder": "Any HOA restrictions, fees, or rules buyers should know."
      },
      {
        "id": "shortTermRentals",
        "label": "Are Short Term Rentals Allowed?",
        "type": "radio",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "projectRestriction",
        "label": "Project Restriction?",
        "type": "radio",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "seniorCommunity",
        "label": "Senior Community?",
        "type": "radio",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "maintenanceFree",
        "label": "Maintenance Free?",
        "type": "radio",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "solar",
        "label": "Does the property have solar?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "solarOwnership",
        "label": "Solar ownership",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Owned",
          "Leased",
          "Financed",
          "Power Purchase Agreement (PPA)"
        ],
        "otherText": false
      },
      {
        "id": "solarYearInstalled",
        "label": "Install date / year installed",
        "type": "text",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 2020 or 06/2020"
      },
      {
        "id": "solarSystemSizeKw",
        "label": "System size (kW)",
        "type": "number",
        "status": "hidden-in-jotform",
        "placeholder": "if known"
      },
      {
        "id": "solarBatteryStorage",
        "label": "Battery storage?",
        "type": "radio",
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "solarLoanOrLien",
        "label": "Loan or lien (e.g. PACE / UCC)?",
        "type": "radio",
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "solarDocsAvailable",
        "label": "Documents available to upload later?",
        "type": "radio",
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "solarCompanyName",
        "label": "Leasing Company",
        "type": "text",
        "status": "hidden-in-jotform"
      },
      {
        "id": "solarFinanceCompany",
        "label": "Finance Company",
        "type": "text",
        "status": "hidden-in-jotform"
      },
      {
        "id": "solarMonthlyPayment",
        "label": "Approx. monthly payment",
        "type": "currency",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., $120"
      },
      {
        "id": "solarAgreementTerm",
        "label": "Remaining term / expiration",
        "type": "text",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 12 years left or Dec 2035"
      },
      {
        "id": "solarTransferable",
        "label": "Agreement transferable to buyer?",
        "type": "radio",
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 5,
    "id": "property-details",
    "title": "Property Details",
    "intro": null,
    "fields": [
      {
        "id": "q11-propertytype",
        "label": "Property type",
        "type": "radio",
        "required": true,
        "options": [
          "Single Family",
          "Condominium",
          "Mobile (w/o land)",
          "Recreational",
          "Townhouse",
          "Twin"
        ],
        "otherText": false
      },
      {
        "id": "pud",
        "label": "Is this a PUD (Planned Unit Development)?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "pid",
        "label": "Is this a PID (Public Infrastructure District)?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "constructionStatus",
        "label": "Construction Status",
        "type": "radio",
        "required": true,
        "options": [
          "Built/Standing",
          "Under Construction",
          "To Be Built"
        ],
        "otherText": false
      },
      {
        "id": "q51-styleof51",
        "type": "radio",
        "required": true,
        "label": "Style of property",
        "options": [
          "2-Story",
          "A-Frame",
          "Basement",
          "Bungalow/Cottage",
          "Cabin",
          "Condo, High Rise",
          "Condo, Main Level",
          "Condo, Middle Level",
          "Condo, Studio",
          "Condo, Top Level",
          "Manufactured",
          "Mid-Century Modern",
          "Mobile",
          "Modern",
          "Modular",
          "Patio Home",
          "Rambler/Ranch",
          "Southwest",
          "Split-Entry/Bi-Level",
          "Townhouse, Row-End",
          "Townhouse, Row-Mid",
          "Tri/Multi-Level",
          "Tudor",
          "Victorian",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "yearBuilt",
        "label": "Year Built",
        "type": "number",
        "required": true,
        "placeholder": "e.g., 1998"
      },
      {
        "id": "effectiveYearBuilt",
        "label": "Effective Year Built",
        "type": "number",
        "placeholder": "e.g., 1998",
        "description": "Leave blank if same as year built."
      },
      {
        "id": "noAssignedParcelNumber",
        "label": "No assigned parcel number?",
        "type": "radio",
        "required": true,
        "options": [
          "No",
          "Yes"
        ],
        "description": "Choose Yes only if the property has no tax parcel / APN assigned yet (e.g. new construction).",
        "otherText": false
      },
      {
        "id": "taxParcelNumber",
        "label": "Tax Parcel Number (APN)",
        "type": "text",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 12-34-56-789",
        "description": "Enter the parcel number from your property tax statement if known."
      },
      {
        "id": "estimatedTaxes",
        "label": "Estimated Taxes ($)",
        "type": "currency",
        "placeholder": "e.g., $3,200",
        "description": "Annual estimated property taxes, if known."
      },
      {
        "id": "waterShares",
        "label": "Water Shares",
        "type": "text",
        "placeholder": "e.g., 2 shares — Canal Co.",
        "description": "Optional. Describe any irrigation or water company shares."
      },
      {
        "id": "lotSize",
        "label": "Lot Size (Acres)",
        "type": "text",
        "required": true,
        "placeholder": "e.g., .23",
        "description": "What size is the parcel?"
      },
      {
        "id": "lotFrontage",
        "label": "Frontage",
        "type": "text",
        "placeholder": "e.g., 80 ft",
        "description": "Lot frontage measurement, if known."
      },
      {
        "id": "lotSide",
        "label": "Side",
        "type": "text",
        "placeholder": "e.g., 120 ft",
        "description": "Lot side measurement, if known."
      },
      {
        "id": "lotBack",
        "label": "Back",
        "type": "text",
        "placeholder": "e.g., 80 ft",
        "description": "Lot back measurement, if known."
      },
      {
        "id": "lotIrregularShape",
        "label": "Irregular Shape?",
        "type": "radio",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "frontageFacing",
        "label": "Frontage Facing",
        "type": "radio",
        "options": [
          "N",
          "S",
          "E",
          "W",
          "NE",
          "SE",
          "NW",
          "SW"
        ],
        "description": "Direction the front of the lot faces.",
        "otherText": false
      },
      {
        "id": "livingSqft",
        "label": "Approximate Total Living Square Footage",
        "type": "number",
        "required": true
      },
      {
        "id": "adu",
        "label": "Does the property have an Accessory Dwelling Unit (ADU)?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduType",
        "label": "ADU Type",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Attached",
          "Detached"
        ],
        "otherText": false
      },
      {
        "id": "aduSqft",
        "label": "ADU Approximate Sq. Ft.",
        "type": "number",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 650"
      },
      {
        "id": "aduBeds",
        "label": "ADU Beds",
        "type": "number",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 1"
      },
      {
        "id": "aduBaths",
        "label": "ADU Baths",
        "type": "text",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 1 or 1.5"
      },
      {
        "id": "aduKitchen",
        "label": "ADU Kitchen?",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduSeparateEntrance",
        "label": "ADU Separate Entrance?",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduSeparateWaterMeter",
        "label": "ADU Separate Water Meter?",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduSeparateGasMeter",
        "label": "ADU Separate Gas Meter?",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduSeparateElectricMeter",
        "label": "ADU Separate Electric Meter?",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduCurrentlyRented",
        "label": "Is the ADU currently rented?",
        "type": "radio",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "aduMonthlyRent",
        "label": "Current Monthly Rent",
        "type": "currency",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "e.g., $1,200"
      },
      {
        "id": "aduRemarks",
        "label": "ADU Remarks",
        "type": "textarea",
        "status": "hidden-in-jotform",
        "placeholder": "Anything buyers should know about the ADU."
      }
    ]
  },
  {
    "order": 6,
    "id": "level-breakdown",
    "title": "Breakdown By Level",
    "intro": "We apologize that this section may be difficult via a mobile device.\n\nHowever, this is how the MLS distributes and formats your information. The more accurate this information, the more buyers you will reach.\n\n(If you don't have the approximate square feet per level, just leave blank and we can look it up for you. We do need the other information filled out accurately)\n\nEx: Basement + Main Level + Second Story = 3 Levels\nEx: Multi Level could be 3 or 4 depending on the basement.\n",
    "fields": [
      {
        "id": "levelCount",
        "label": "How Many Levels In The Property?",
        "type": "radio",
        "required": true,
        "options": [
          "1",
          "2",
          "3",
          "4",
          "5"
        ],
        "otherText": false
      },
      {
        "id": "q26-typea26",
        "label": "Basement / Lower Level Type",
        "type": "checkbox",
        "required": true,
        "options": [
          "Daylight",
          "Entrance",
          "Full",
          "Walkout",
          "Shelf",
          "Partial",
          "None / Crawlspace / Slab",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "basementFinished",
        "label": "Basement Finished",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No",
          "Partial",
          "N/A"
        ],
        "otherText": false
      },
      {
        "id": "q117-2level117",
        "type": "matrix",
        "label": "Please add the corresponding information for each level. (Scroll right to see all info)",
        "columns": [
          {
            "id": "square-footage",
            "label": "Square Footage(+/-)",
            "type": "number"
          },
          {
            "id": "bedrooms",
            "label": "Bedrooms",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7"
            ]
          },
          {
            "id": "master-y-n",
            "label": "Master (Y/N)",
            "type": "checkbox"
          },
          {
            "id": "full-baths",
            "label": "Full Baths",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6"
            ]
          },
          {
            "id": "3-4-baths",
            "label": "3/4 Baths",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6"
            ]
          },
          {
            "id": "1-2-baths",
            "label": "1/2 Baths",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6"
            ]
          },
          {
            "id": "family",
            "label": "Family",
            "type": "checkbox"
          },
          {
            "id": "den",
            "label": "Den",
            "type": "checkbox"
          },
          {
            "id": "formal-living",
            "label": "Formal Living",
            "type": "checkbox"
          },
          {
            "id": "kitchen",
            "label": "Kitchen (K)",
            "type": "checkbox"
          },
          {
            "id": "breakfast",
            "label": "Breakfast (B)",
            "type": "checkbox"
          },
          {
            "id": "formal-dining",
            "label": "Formal Dining (F)",
            "type": "checkbox"
          },
          {
            "id": "semi-formal",
            "label": "Semi-formal (S)",
            "type": "checkbox"
          },
          {
            "id": "laundry",
            "label": "Laundry",
            "type": "checkbox"
          },
          {
            "id": "fireplace",
            "label": "Fireplace",
            "type": "checkbox"
          }
        ],
        "dynamic": {
          "rowCountFrom": "levelCount",
          "rowLabels": [
            "Main Level",
            "Basement"
          ]
        }
      }
    ]
  },
  {
    "order": 7,
    "id": "interior-systems",
    "title": "Interior Systems",
    "intro": null,
    "fields": [
      {
        "id": "q33-flooring",
        "type": "checkbox",
        "label": "Flooring",
        "required": true,
        "description": "Select all that apply, or choose None if unknown.",
        "options": [
          "None",
          "Bamboo",
          "Carpet",
          "Concrete",
          "Cork",
          "Hardwood",
          "Laminate",
          "Linoleum",
          "Marble",
          "Natural Rock",
          "Slate",
          "Tile",
          "Travertine",
          "Vinyl",
          "Vinyl (LVP)",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q34-typea34",
        "type": "checkbox",
        "label": "Interior Special Features",
        "required": false,
        "description": "Select any that apply, or leave blank if none.",
        "options": [
          "None",
          "Accessory Apartment",
          "Alarm: Fire",
          "Alarm: Security",
          "Bar: Dry",
          "Bar: Wet",
          "Basement Apartment",
          "Bath: Primary",
          "Bath: Sep. Tub / Shower",
          "Central Vacuum",
          "Closet: Walk-in",
          "Den / Office",
          "Dishwasher, Built-in",
          "Disposal",
          "Floor Drains",
          "French Doors",
          "Gas Log",
          "Granite Countertops",
          "Great Room",
          "Instantaneous Hot Water",
          "Intercom",
          "Jetted Tub",
          "Kitchen: Second",
          "Kitchen: Updated",
          "Laundry Chute",
          "Low VOC Finishes",
          "Marble Countertops",
          "Mother-in-law Apt.",
          "Oven: Double",
          "Oven: Gas",
          "Oven: Wall",
          "Quartz Countertops",
          "Range / Oven, Built-in",
          "Range / Oven, Free Stdng.",
          "Range, Countertop",
          "Range, Down Vent",
          "Range, Gas",
          "Silestone Countertops",
          "Theater Room",
          "Vaulted Ceilings",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q27-typea27",
        "type": "checkbox",
        "label": "Accessibility Features",
        "required": true,
        "description": "Select all that apply, or choose None if not applicable.",
        "options": [
          "None",
          "32\" Wide Doorways",
          "36\" Wide Hallways",
          "Access to Elec. Outlet",
          "Audible Alerts",
          "Ceiling Lift System",
          "Elevator",
          "Frnt-Cntrld Stove / Oven",
          "Fully Accessible",
          "Grab Bars",
          "Ground Level",
          "Modified Kitchen",
          "No-Step Entry",
          "Porch Lift",
          "Ramp",
          "Roll-In Shower",
          "Single Level Living",
          "Stair Lift",
          "Universal Design",
          "Visible Alerts",
          "Visitable",
          "Wheelchair Access",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q41-window-coverings",
        "type": "checkbox",
        "label": "Window Coverings",
        "required": true,
        "description": "Select all that apply, or choose None if not applicable.",
        "options": [
          "Blinds",
          "Draperies",
          "Full",
          "None",
          "Part",
          "Plantation Shutters",
          "Shades",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q42-amenities",
        "type": "checkbox",
        "label": "Amenities",
        "required": false,
        "description": "Select community or property amenities that apply, or leave blank if none.",
        "options": [
          "None",
          "Cable TV Available",
          "Cable TV Wired",
          "Clubhouse",
          "Electric Dryer Hookup",
          "Exercise Room",
          "Gas Dryer Hookup",
          "Gated Community",
          "Home Warranty",
          "Park / Playground",
          "Pickleball Court",
          "Sauna / Steam Room",
          "Ski-In/Ski-Out",
          "Swimming Pool",
          "Tennis Court",
          "Workshop",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q31-airconditioning",
        "type": "checkbox",
        "label": "Air Conditioning",
        "required": true,
        "description": "Select all that apply, or choose None if not applicable.",
        "options": [
          "None",
          "Active Solar",
          "Central Air; Electric",
          "Central Air; Gas",
          "Evap. Cooler: Roof",
          "Evap. Cooler: Window",
          "Geothermal",
          "Heat Pump",
          "Passive Solar",
          "Natural Ventilation",
          "Refrig. Air; Window",
          "Seer 16 Or Higher",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q96-hvac96",
        "type": "checkbox",
        "label": "Heating",
        "required": true,
        "description": "Select all that apply, or choose None if unknown.",
        "options": [
          "None",
          ">= 95% efficiency",
          "Active Solar",
          "Electric",
          "Electric: Baseboard",
          "Electric: Radiant",
          "Forced Air",
          "Gas: Central",
          "Gas: Radiant",
          "Gas: Stove",
          "Geothermal",
          "Gravity Heater",
          "Heat Pump",
          "Heat Recovery",
          "Hot Water",
          "Hydronic",
          "Oil",
          "Passive Solar",
          "Propane",
          "Radiant: In Floor",
          "Space Heater",
          "Steam",
          "Wall Heater",
          "Wood Burning",
          "See Remarks"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 8,
    "id": "exterior-parking",
    "title": "Exterior & Parking",
    "intro": null,
    "fields": [
      {
        "id": "q32-typea32",
        "type": "checkbox",
        "label": "Exterior",
        "required": true,
        "options": [
          "Aluminum",
          "Asbestos Shingles",
          "Asphalt Shingles",
          "Brick",
          "Cedar",
          "Cement Board",
          "Cinder Block",
          "Clapboard/Masonite",
          "Composition",
          "Concrete",
          "Container",
          "Frame",
          "Glass",
          "Insulated Concrete Forms",
          "Log",
          "Metal",
          "Other Wood",
          "Redwood",
          "Stone",
          "Straw Bale",
          "Stucco",
          "Vinyl",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q29-typea29",
        "type": "checkbox",
        "label": "Exterior Special Features",
        "required": false,
        "description": "Select any that apply, or leave blank if none.",
        "options": [
          "None",
          "Atrium",
          "Attic Fan",
          "Awnings",
          "Balcony",
          "Barn",
          "Basement Entrance",
          "Bay Box Windows",
          "Deck: Covered",
          "Double Pane Windows",
          "Entry (Foyer)",
          "Greenhouse Windows",
          "Horse Property",
          "Out Buildings",
          "Outdoor Lighting",
          "Patio: Covered",
          "Patio: Open",
          "Porch: Open",
          "Porch: Screened",
          "Secured Building",
          "Secured Parking",
          "Skylights",
          "Sliding Glass Doors",
          "Stained Glass Windows",
          "Storm Doors",
          "Storm Windows",
          "Triple Pane Windows",
          "Walk Out",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "deckCount",
        "type": "number",
        "label": "# of Decks",
        "placeholder": "e.g., 1",
        "description": "Total number of decks on the property, if any."
      },
      {
        "id": "patioCount",
        "type": "number",
        "label": "# of Patios",
        "placeholder": "e.g., 1",
        "description": "Total number of patios on the property, if any."
      },
      {
        "id": "q30-typea30",
        "type": "checkbox",
        "label": "Garage / Parking",
        "required": true,
        "options": [
          "2 Car Deep (Tandem)",
          "Attached",
          "Built-in",
          "Detached",
          "Electrical Vehicle Charging Station",
          "Extra Height",
          "Extra Length",
          "Extra Width",
          "Heated",
          "Opener",
          "Parking: Covered",
          "Parking: Uncovered",
          "RV Electrical Hookup",
          "RV Parking",
          "Storage Above",
          "Workbench",
          "Workshop",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q208-garagecapacity",
        "type": "number",
        "label": "Garage Capacity",
        "status": "hidden-in-jotform",
        "min": 1,
        "max": 10,
        "default": 2
      },
      {
        "id": "q209-garagecapacity209",
        "type": "number",
        "label": "Carport Capacity",
        "status": "hidden-in-jotform",
        "min": 1,
        "max": 10,
        "default": 1
      },
      {
        "id": "parkingCapacity",
        "type": "number",
        "label": "Parking Capacity",
        "placeholder": "e.g., 2",
        "description": "Total parking spaces (driveway / open parking), if known."
      },
      {
        "id": "rvParkingHeight",
        "type": "text",
        "label": "R.V. Parking Height",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 12 ft"
      },
      {
        "id": "rvParkingLength",
        "type": "text",
        "label": "R.V. Parking Length",
        "status": "hidden-in-jotform",
        "placeholder": "e.g., 40 ft"
      },
      {
        "id": "q28-typea28",
        "type": "checkbox",
        "label": "Driveway",
        "required": true,
        "options": [
          "Asphalt",
          "Circular",
          "Common Drive",
          "Concrete",
          "Dirt",
          "Gravel",
          "Heated",
          "See Remarks"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 9,
    "id": "pool-roof-yard",
    "title": "Pool, Roof & Yard",
    "intro": null,
    "fields": [
      {
        "id": "q184-doesthe",
        "type": "radio",
        "label": "Pool Available?",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "q63-pooltype",
        "type": "checkbox",
        "label": "If Yes, please specify (Pool Features)",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Above Ground",
          "Concrete/Gunite",
          "Electronic Cover",
          "Fenced",
          "Fiberglass/Vinyl",
          "Heated",
          "In Ground",
          "Indoor",
          "With Spa",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "spaAvailable",
        "type": "radio",
        "label": "Spa Available?",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "communityPool",
        "type": "radio",
        "label": "Community Pool?",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "q37-typea37",
        "type": "checkbox",
        "label": "Roof",
        "required": true,
        "options": [
          "Aluminum",
          "Asbestos Shingles",
          "Asphalt Shingles",
          "Bitumen",
          "Composition",
          "Fiberglass",
          "Flat",
          "Membrane",
          "Metal",
          "Pitched",
          "PVC",
          "Rolled-silver",
          "Rubber (EPDM)",
          "Stone",
          "Tar / Gravel",
          "Tile",
          "Wood Shake Shingles",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q36-typea36",
        "type": "checkbox",
        "label": "Landscaping",
        "required": true,
        "options": [
          "None",
          "Fruit Trees",
          "Landscaping: Full",
          "Landscaping: Part",
          "Mature Trees",
          "Pines",
          "Scrub Oak",
          "Stream",
          "Terraced Yard",
          "Vegetable Garden",
          "Waterfall",
          "Xeriscaped",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q43-lot-facts",
        "type": "checkbox",
        "label": "Lot Facts",
        "required": true,
        "options": [
          "None",
          "Additional Land Available",
          "Adjacent to Golf Course",
          "Corner Lot",
          "Cul-de-sac",
          "Curb & Gutter",
          "Drip Irrigation: Auto-full",
          "Drip Irrigation: Auto-part",
          "Drip Irrigation: Manual-full",
          "Drip Irrigation: Manual-part",
          "Fenced, Full",
          "Fenced, Part",
          "Greywater Collection",
          "Pervious Paving",
          "Private",
          "Rainwater Collection",
          "Road: Paved",
          "Road: Unpaved",
          "Secluded Yard",
          "Sidewalks",
          "Sprinkler: Auto-full",
          "Sprinkler: Auto-part",
          "Sprinkler: Manual-full",
          "Sprinkler: Manual-part",
          "Terrain: Flat",
          "Terrain: Grad Slope",
          "Terrain: Hilly",
          "Terrain: Mountain",
          "Terrain: Steep Slope",
          "View: Lake",
          "View: Mountain",
          "View: Red Rock",
          "View: Valley",
          "View: Water",
          "Waterfront",
          "Wooded",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "petsAllowed",
        "label": "Pets Allowed?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "q47-animals",
        "type": "checkbox",
        "label": "Animals",
        "required": true,
        "status": "hidden-in-jotform",
        "description": "Select all that apply.",
        "options": [
          "Pets < 20 Lbs.",
          "Pets 20 - 75 Lbs.",
          "Pets > 75 Lbs.",
          "Livestock",
          "Other"
        ],
        "otherText": true
      }
    ]
  },
  {
    "order": 10,
    "id": "utilities-zoning-terms",
    "title": "Utilities, Zoning & Terms",
    "intro": null,
    "fields": [
      {
        "id": "q39-typea39",
        "type": "checkbox",
        "label": "Storage",
        "required": true,
        "options": [
          "Basement",
          "Carport",
          "Garage",
          "Other",
          "Patio",
          "Shed",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q35-connectedutilities",
        "type": "checkbox",
        "label": "Utilities",
        "required": true,
        "options": [
          "Gas: Available",
          "Gas: Connected",
          "Gas: Not Available",
          "Gas: Not Connected",
          "Power: Available",
          "Power: Connected",
          "Power: Not Available",
          "Power: Not Connected",
          "Sewer: Available",
          "Sewer: Connected",
          "Sewer: Not Available",
          "Sewer: Not Connected",
          "Sewer: Private",
          "Sewer: Public",
          "Sewer: Septic Tank",
          "Water: Available",
          "Water: Connected",
          "Water: Not Available",
          "Water: Not Connected",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q44-water",
        "type": "checkbox",
        "label": "Water",
        "required": true,
        "description": "Select all water sources that apply.",
        "options": [
          "Culinary",
          "Irrigation",
          "Irrigation: Pressure",
          "Private",
          "Rights: Owned",
          "Rights: Rented",
          "Secondary",
          "Shares",
          "Spring",
          "Well",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q45-telecommunications",
        "type": "checkbox",
        "label": "Telecommunications",
        "required": true,
        "options": [
          "Broadband Cable",
          "DSL",
          "Ethernet, Wired",
          "Fiber",
          "Multiple Phone Lines",
          "T-1 Line",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q46-environmental-certs",
        "type": "checkbox",
        "label": "Environmental Certifications",
        "options": [
          "None",
          "Built Green",
          "Energy Star",
          "Home Energy Rating",
          "Leed",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q38-zoning",
        "type": "checkbox",
        "label": "Zoning",
        "required": true,
        "options": [
          "Agricultural",
          "Commercial",
          "Industrial",
          "Multi-Family",
          "Short Term Rental Allowed",
          "Single-Family",
          "See Remarks"
        ],
        "otherText": false
      },
      {
        "id": "q40-typea40",
        "type": "checkbox",
        "label": "Terms (acceptable terms of sale)",
        "required": true,
        "options": [
          "Assumption: Qualify",
          "Assumption: Simple",
          "Cash",
          "Commercial Fin. Req.",
          "Conventional",
          "Conventional Rehabilitation Loan",
          "Cryptocurrency",
          "Down Payment Assist.",
          "Exchange",
          "FHA",
          "FHA 203(k) - Rehabilitation",
          "Lease Option Monthly",
          "Lease Option Yearly",
          "Owner 2nd",
          "Seller Finance",
          "Seller Will Subordinate",
          "USDA Rural Development",
          "VA",
          "See Remarks"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 11,
    "id": "personal-property",
    "title": "Personal Property / Conveyances",
    "intro": null,
    "fields": [
      {
        "id": "q19-typea19",
        "label": "Inclusions / Exclusions",
        "type": "matrix",
        "description": "For each item, check Include (conveys with the sale) or Exclude (does not convey). Leave both blank if neither applies.",
        "columns": [
          {
            "id": "include",
            "label": "Include",
            "type": "checkbox"
          },
          {
            "id": "exclude",
            "label": "Exclude",
            "type": "checkbox"
          }
        ],
        "rows": [
          "Alarm System",
          "Basketball Standard",
          "Ceiling Fan",
          "Compactor",
          "Dishwasher: Portable",
          "Dog Run",
          "Dryer",
          "Electric Air Cleaner",
          "Fireplace Equipment",
          "Fireplace Insert",
          "Freezer",
          "Gas Grill / BBQ",
          "Gazebo",
          "Hot Tub",
          "Humidifier",
          "Microwave",
          "Play Gym",
          "Projector",
          "Range",
          "Range Hood",
          "Refrigerator",
          "Satellite Dish",
          "Satellite Equipment",
          "Smart Thermostat(s)",
          "Storage Shed(s)",
          "Swing Set",
          "Trampoline",
          "TV Antenna",
          "Video Camera(s)",
          "Video Door Bell(s)",
          "Washer",
          "Water Softener: Own",
          "Water Softener: Rent",
          "Window Coverings",
          "Wood Stove",
          "Workbench",
          "See Remarks"
        ]
      }
    ]
  },
  {
    "order": 12,
    "id": "buyer-showings",
    "title": "Buyer Showings",
    "intro": null,
    "fields": [
      {
        "id": "field-81",
        "type": "content",
        "content": "BUYER SHOWINGS\nPlease let us know if the property is owner occupied, tenant occupied or vacant and who is authorized to approve buyer showings with their contact information.\nShowing approvals can be made via text message & email. \nWe will deliver a secure electronic lock box and it will be placed on or around the front door area.  This box can ONLY be accessed by licensed agents once they have scheduled an appointment. \n"
      },
      {
        "id": "q191-propertyoccupancy",
        "type": "radio",
        "label": "Property Occupancy",
        "required": true,
        "options": [
          "Owner Occupied",
          "Tenant Occupied",
          "Vacant / Immediate Appt Approval"
        ],
        "otherText": false
      },
      {
        "id": "q192-howmany",
        "type": "radio",
        "label": "How Many Owners Can Approve Showings?",
        "status": "hidden-in-jotform",
        "options": [
          "One",
          "Two"
        ],
        "otherText": false
      },
      {
        "id": "q193-howmany193",
        "type": "radio",
        "label": "How Many Tenants Can Approve Showings?",
        "status": "hidden-in-jotform",
        "options": [
          "One",
          "Two"
        ],
        "otherText": false
      },
      {
        "id": "q194-ownershowing",
        "type": "fullname",
        "label": "Owner Showing Contact 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q195-phonenumber",
        "type": "phone",
        "label": "Owner Showing Phone 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q196-email",
        "type": "email",
        "label": "Owner Showing Email 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q197-ownershowing197",
        "type": "fullname",
        "label": "Owner Showing Contact 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q198-ownershowing198",
        "type": "phone",
        "label": "Owner Showing Phone 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q199-ownershowing199",
        "type": "email",
        "label": "Owner Showing Email 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q200-tenantshowing",
        "type": "fullname",
        "label": "Tenant Showing Contact 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q201-ownershowing201",
        "type": "phone",
        "label": "Tenant Showing Phone 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q202-tenantshowing202",
        "type": "email",
        "label": "Tenant Showing Email 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q203-tenantshowing203",
        "type": "fullname",
        "label": "Tenant Showing Contact 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q204-tenantshowing204",
        "type": "phone",
        "label": "Tenant Showing Phone 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q205-tenantshowing205",
        "type": "email",
        "label": "Tenant Showing Email 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q100-showinginstructions",
        "type": "textarea",
        "label": "Showing Instructions (remarks)",
        "placeholder": "Please share any important access information and how to handle those items. (Pets, Alarms, Tenants, etc.)  Please be as detailed as possible."
      },
      {
        "id": "showInstructions",
        "type": "checkbox",
        "label": "Show Instructions",
        "required": false,
        "description": "Select all that apply for the Data Form (optional — occupancy still used as a fallback).",
        "options": [
          "Agent Has Key",
          "Appt / Use Lockbox",
          "Call Agent / Appt",
          "Call Owner / Appt",
          "Call Showing Service",
          "Call Tenant / Appt",
          "Call Use / Lockbox",
          "Combination Box",
          "Key At List Office",
          "Key Box: Electronic",
          "Knock / Use Lockbox",
          "Use Aligned Showings",
          "Use Showing Service",
          "Vacant",
          "See Remarks"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 13,
    "id": "title-company",
    "title": "Title Company",
    "intro": null,
    "fields": [
      {
        "id": "field-210",
        "type": "content",
        "content": "Title Company\nWould you like us to open your title work with Prime Title Co?\n(This will expedite the process and they will be notified upon listing)\n"
      },
      {
        "id": "q207-typea207",
        "type": "radio",
        "options": [
          "Yes",
          "No, I have someone else"
        ],
        "otherText": false
      },
      {
        "id": "q211-name211",
        "type": "fullname",
        "label": "Title Co Contact",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q212-typea212",
        "type": "text",
        "label": "Title Company Name",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q213-email213",
        "type": "email",
        "label": "Title Co Email",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q214-phonenumber214",
        "type": "phone",
        "label": "Title Company Phone",
        "status": "hidden-in-jotform"
      }
    ]
  },
  {
    "order": 14,
    "id": "remarks",
    "title": "Remarks",
    "intro": null,
    "fields": [
      {
        "id": "q97-publicremarks",
        "type": "textarea",
        "label": "Public Remarks / House Description",
        "placeholder": "Please give a description of the home highlighting it's best features.  We may modify it with your approval prior to posting on the MLS."
      },
      {
        "id": "exclusionsRemarks",
        "type": "textarea",
        "label": "Exclusions Remarks",
        "placeholder": "List any items explicitly excluded from the sale."
      },
      {
        "id": "q98-commentsto",
        "type": "textarea",
        "label": "Comments To Utah Digs",
        "placeholder": "These comments will only be seen by us.  Any special features, situations, concerns etc."
      }
    ]
  },
  {
    "order": 15,
    "id": "photos",
    "title": "Photos",
    "intro": null,
    "fields": [
      {
        "id": "field-218",
        "type": "content",
        "content": "Photos\nIf you have your own photos you can upload now. We recommend uploading later in your seller app/portal under \"manage your listing\" to avoid resetting this form if files are too large. We will need 2 exterior and 3 interior photos minimum to list on the MLS.\n** A professional photo tour is included with the Full Service Listing and will be scheduled upon receipt of your listing agreement and this form**\n"
      },
      {
        "id": "field-44",
        "label": "Property photos",
        "type": "file",
        "multiple": true
      }
    ]
  },
  {
    "order": 16,
    "id": "signature",
    "title": "Signature",
    "intro": null,
    "fields": [
      {
        "id": "field-217",
        "type": "content",
        "content": "The Undersigned represents and acknowledges that Undersigned is the owner of the real property described in this Listing Input Form (“Owner”). Owner acknowledges that Wasatch Front Regional Multiple Listing Service, Inc. (“WFRMLS”) maintains a multiple listing service database for brokers, agents, and the public (“MLS Compilation”) and consents to all of the information included in this Listing Input Form (“Listing Content”) being included in the MLS Compilation.\nOwner hereby grants WFRMLS a license to the Listing Content for the following purposes, among others: display of the Listing Content in the MLS Compilation, distribution and sublicensing of the Listing Content to third parties for display and use by third parties, display of the Listing Content on UtahRealEstate.com and any other WFRMLS owned websites, and any other lawful use. Owner hereby represents and warrants that Owner has all right, title, and interest in and to any copyright rights and other intellectual property rights associated with the Listing Content and that the Listing Content is correct and accurate. Owner agrees to indemnify and hold harmless WFRMLS against all damages, costs and liabilities, including reasonable attorney fees, arising from any claim that the Listing Content or any portion thereof infringes the rights of any third party.\n"
      },
      {
        "id": "q20-signature",
        "type": "signature",
        "label": "Primary Owner Signature",
        "required": true
      },
      {
        "id": "q20-initials",
        "type": "signature",
        "label": "Primary Owner Initials",
        "description": "Your initials will be placed on each page of the Data Form. Draw or type your initials once.",
        "required": true
      },
      {
        "id": "q23-signature23",
        "type": "signature",
        "label": "Secondary Owner Signature (If applicable)",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q23-initials",
        "type": "signature",
        "label": "Secondary Owner Initials (If applicable)",
        "description": "Secondary owner initials for each page of the Data Form.",
        "status": "hidden-in-jotform",
        "required": true
      }
    ]
  }
];

export const MLS_INPUT_STEP_COUNT = MLS_INPUT_STEPS.length;

export function getMlsInputStep(order: number): MlsInputStep | undefined {
  return MLS_INPUT_STEPS.find((s) => s.order === order);
}

export function getAllMlsFieldIds(): string[] {
  const ids: string[] = [];
  for (const step of MLS_INPUT_STEPS) {
    for (const field of step.fields) {
      if (field.type !== "content") ids.push(field.id);
    }
  }
  return ids;
}

export function getFieldById(fieldId: string): MlsInputField | undefined {
  for (const step of MLS_INPUT_STEPS) {
    const field = step.fields.find((f) => f.id === fieldId);
    if (field) return field;
  }
  return undefined;
}
