// AUTO-GENERATED by prototypes/jot-forms/mls-input/scripts/codegen.mjs — do not edit manually

export type MlsInputFieldType =
  | "text"
  | "textarea"
  | "radio"
  | "checkbox"
  | "select"
  | "number"
  | "currency"
  | "email"
  | "phone"
  | "fullname"
  | "address"
  | "matrix"
  | "file"
  | "signature"
  | "content";

export type MlsInputMatrixColumn = {
  id: string;
  label: string;
  type: string;
  options?: string[];
};

export type MlsInputField = {
  id: string;
  label?: string;
  type: MlsInputFieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  description?: string;
  content?: string;
  status?: string;
  rows?: string[];
  columns?: MlsInputMatrixColumn[];
  dynamic?: {
    rowCountFrom?: string;
    rowLabels?: string[];
  };
  otherText?: boolean;
  multiple?: boolean;
  min?: number;
  max?: number;
  default?: number;
};

export type MlsInputStep = {
  order: number;
  id: string;
  title: string;
  intro?: string | null;
  fields: MlsInputField[];
};

export type MlsInputFormValues = {
  "ownerCount"?: string;
  "primaryOwnerName"?: { first: string; last: string };
  "primaryOwnerPhone"?: string;
  "primaryOwnerEmail"?: string;
  "secondaryOwnerName"?: { first: string; last: string };
  "secondaryOwnerPhone"?: string;
  "secondaryOwnerEmail"?: string;
  "listingAddress"?: { street: string; city: string; state: string; zip: string };
  "listingCounty"?: string;
  "listingQuadrant"?: string;
  "listingCoordinates"?: string;
  "nonStandardAddress"?: string;
  "directionsRemarks"?: string;
  "ownerAddressSameAsListing"?: string;
  "ownerAddress"?: { street: string; city: string; state: string; zip: string };
  "listingPrice"?: string;
  "shortSale"?: string;
  "schools"?: Record<string, Record<string, string | string[]>>;
  "hoa"?: string;
  "hoaFeeMonth"?: string;
  "hoaContact"?: string;
  "hoaContactPhone"?: string;
  "shortTermRentals"?: string;
  "solar"?: string;
  "q11-propertytype"?: string;
  "constructionStatus"?: string;
  "q51-styleof51"?: string;
  "yearBuilt"?: string;
  "effectiveYearBuilt"?: string;
  "taxParcelNumber"?: string;
  "lotSize"?: string;
  "livingSqft"?: string;
  "levelCount"?: string;
  "q26-typea26"?: string[];
  "basementFinished"?: string;
  "q117-2level117"?: Record<string, Record<string, string | string[]>>;
  "q33-flooring"?: string[];
  "q34-typea34"?: string[];
  "q27-typea27"?: string[];
  "q41-window-coverings"?: string[];
  "q42-amenities"?: string[];
  "q31-airconditioning"?: string[];
  "q96-hvac96"?: string[];
  "q32-typea32"?: string[];
  "q29-typea29"?: string[];
  "q30-typea30"?: string[];
  "q208-garagecapacity"?: string;
  "q209-garagecapacity209"?: string;
  "q28-typea28"?: string[];
  "q184-doesthe"?: string;
  "q63-pooltype"?: string[];
  "q37-typea37"?: string[];
  "q36-typea36"?: string[];
  "q43-lot-facts"?: string[];
  "q47-animals"?: string;
  "q39-typea39"?: string[];
  "q35-connectedutilities"?: string[];
  "q44-water"?: string[];
  "q45-telecommunications"?: string[];
  "q46-environmental-certs"?: string[];
  "q38-zoning"?: string[];
  "q40-typea40"?: string[];
  "q19-typea19"?: string[];
  "q191-propertyoccupancy"?: string;
  "q192-howmany"?: string;
  "q193-howmany193"?: string;
  "q194-ownershowing"?: { first: string; last: string };
  "q195-phonenumber"?: string;
  "q196-email"?: string;
  "q197-ownershowing197"?: { first: string; last: string };
  "q198-ownershowing198"?: string;
  "q199-ownershowing199"?: string;
  "q200-tenantshowing"?: { first: string; last: string };
  "q201-ownershowing201"?: string;
  "q202-tenantshowing202"?: string;
  "q203-tenantshowing203"?: { first: string; last: string };
  "q204-tenantshowing204"?: string;
  "q205-tenantshowing205"?: string;
  "q100-showinginstructions"?: string;
  "q207-typea207"?: string;
  "q211-name211"?: { first: string; last: string };
  "q212-typea212"?: string;
  "q213-email213"?: string;
  "q214-phonenumber214"?: string;
  "q97-publicremarks"?: string;
  "hoaRemarks"?: string;
  "exclusionsRemarks"?: string;
  "q98-commentsto"?: string;
  "field-44"?: Array<{ name: string; url: string }>;
  "q20-signature"?: string;
  "q23-signature23"?: string;
  inquiryId?: string;
  photos?: Array<{ name: string; url: string }>;
};

export const MLS_INPUT_STEPS: MlsInputStep[] = [
  {
    "order": 1,
    "id": "owners",
    "title": "Owners",
    "intro": null,
    "fields": [
      {
        "id": "ownersIntro",
        "type": "content",
        "content": "If there are more than 2 owners or you need to sign for an entity (LLC, Partnership etc), Please select 1 owner and reply to the email you receive when this information is submitted.\n\nOnce this form is complete and we have your email, we can then send the form to the other parties for their signature and/or will collect the operating agreements etc. verifying proof of ownership and/or the right to sign as an officer for the entity prior to placing the property on the MLS.\n"
      },
      {
        "id": "ownerCount",
        "label": "How Many Owners Of The Property?",
        "type": "radio",
        "required": true,
        "options": [
          "One",
          "Two"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 2,
    "id": "primary-owner",
    "title": "Primary Owner",
    "intro": null,
    "fields": [
      {
        "id": "primaryOwnerName",
        "label": "Primary Owner Name",
        "type": "fullname",
        "required": true
      },
      {
        "id": "primaryOwnerPhone",
        "label": "Primary Owner Phone Number",
        "type": "phone",
        "required": true,
        "placeholder": "(000) 000-0000"
      },
      {
        "id": "primaryOwnerEmail",
        "label": "Primary Owner Email",
        "type": "email",
        "required": true,
        "placeholder": "example@example.com"
      },
      {
        "id": "secondaryOwnerName",
        "label": "Secondary Owner Name",
        "type": "fullname",
        "required": true,
        "status": "hidden-in-jotform"
      },
      {
        "id": "secondaryOwnerPhone",
        "label": "Secondary Owner Phone Number",
        "type": "phone",
        "required": true,
        "placeholder": "(000) 000-0000",
        "status": "hidden-in-jotform"
      },
      {
        "id": "secondaryOwnerEmail",
        "label": "Secondary Owner Email",
        "type": "email",
        "required": true,
        "placeholder": "example@example.com",
        "status": "hidden-in-jotform"
      }
    ]
  },
  {
    "order": 3,
    "id": "listing-address-schools",
    "title": "Listing Address & Schools",
    "intro": null,
    "fields": [
      {
        "id": "listingAddress",
        "label": "Listing Address",
        "type": "address",
        "required": true,
        "description": "Street address of the property being listed."
      },
      {
        "id": "listingCounty",
        "label": "County",
        "type": "text",
        "required": true,
        "placeholder": "e.g., Salt Lake"
      },
      {
        "id": "listingQuadrant",
        "label": "Quadrant",
        "type": "radio",
        "status": "hidden-in-jotform",
        "description": "NW, NE, SW, or SE area of the city (WFRMLS requirement).",
        "options": [
          "NW",
          "NE",
          "SW",
          "SE"
        ],
        "otherText": false
      },
      {
        "id": "listingCoordinates",
        "label": "Approximate North / South & East / West Coordinates",
        "type": "text",
        "placeholder": "ex: 2100 S 1300 E",
        "description": "Optional if the street address above is complete."
      },
      {
        "id": "nonStandardAddress",
        "label": "Is this a non-standard address?",
        "type": "radio",
        "required": true,
        "description": "Choose Yes if the property is hard to find from the street address alone (for example rural, gated, or no formal street address). You will be asked for directions.",
        "options": [
          "No",
          "Yes"
        ],
        "otherText": false
      },
      {
        "id": "directionsRemarks",
        "label": "Directions / Non-Standard Address",
        "type": "textarea",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "Describe how to find the property if the address alone is not sufficient."
      },
      {
        "id": "ownerAddressSameAsListing",
        "label": "Is the OWNER address the SAME as the LISTING address?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "ownerAddress",
        "label": "Owner Address",
        "type": "address",
        "required": true,
        "status": "hidden-in-jotform"
      },
      {
        "id": "listingPrice",
        "label": "Listing Price",
        "type": "currency",
        "required": true,
        "placeholder": "e.g., $500,000"
      },
      {
        "id": "shortSale",
        "label": "Short Sale Status",
        "type": "radio",
        "required": true,
        "options": [
          "Not Short Sale",
          "Price Subject to 3rd Party Approval",
          "Price Previously Approved by 3rd Party",
          "Offer Under 3rd Party Review"
        ],
        "otherText": false
      },
      {
        "id": "schools",
        "label": "Schools",
        "type": "matrix",
        "required": true,
        "rows": [
          "School District",
          "Elementary School",
          "Junior High/Middle School",
          "High School"
        ],
        "columns": [
          {
            "id": "name",
            "label": "NAME",
            "type": "text"
          }
        ]
      }
    ]
  },
  {
    "order": 4,
    "id": "hoa-solar",
    "title": "HOA & Solar",
    "intro": null,
    "fields": [
      {
        "id": "hoa",
        "label": "Is the property in an HOA?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "hoaFeeMonth",
        "label": "HOA Fee / Month",
        "type": "currency",
        "required": true,
        "status": "hidden-in-jotform",
        "placeholder": "e.g., $150"
      },
      {
        "id": "hoaContact",
        "label": "HOA Contact Name",
        "type": "text",
        "status": "hidden-in-jotform"
      },
      {
        "id": "hoaContactPhone",
        "label": "HOA Contact Phone",
        "type": "phone",
        "status": "hidden-in-jotform"
      },
      {
        "id": "shortTermRentals",
        "label": "Are Short Term Rentals Allowed?",
        "type": "radio",
        "options": [
          "Yes",
          "No",
          "Unknown"
        ],
        "otherText": false
      },
      {
        "id": "solar",
        "label": "Does the property have solar?",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      }
    ]
  },
  {
    "order": 5,
    "id": "property-details",
    "title": "Property Details",
    "intro": null,
    "fields": [
      {
        "id": "q11-propertytype",
        "label": "Property type",
        "type": "radio",
        "required": true,
        "options": [
          "Single Family",
          "Condominium",
          "Mobile (w/o land)",
          "Recreational",
          "Townhouse",
          "Twin",
          "P.U.D."
        ],
        "otherText": false
      },
      {
        "id": "constructionStatus",
        "label": "Construction Status",
        "type": "radio",
        "required": true,
        "options": [
          "Built/Standing",
          "Under Construction",
          "To Be Built"
        ],
        "otherText": false
      },
      {
        "id": "q51-styleof51",
        "type": "radio",
        "required": true,
        "label": "Style of property",
        "options": [
          "2-Story",
          "Bungalow / Cottage",
          "Rambler / Ranch Style",
          "Mid-Century Modern",
          "Cabin",
          "Manufactured",
          "Mobile",
          "Split Entry / Bi-Level",
          "Tri / Multi-Level",
          "Townhouse",
          "Townhouse, Row End",
          "Tudor",
          "Victorian",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "yearBuilt",
        "label": "Year Built",
        "type": "number",
        "required": true,
        "placeholder": "e.g., 1998"
      },
      {
        "id": "effectiveYearBuilt",
        "label": "Effective Year Built",
        "type": "number",
        "placeholder": "e.g., 1998",
        "description": "Leave blank if same as year built."
      },
      {
        "id": "taxParcelNumber",
        "label": "Tax Parcel Number (APN)",
        "type": "text",
        "required": false,
        "placeholder": "Leave blank if unknown — we will look it up",
        "description": "Enter the parcel number from your property tax statement if known. Leave blank if the seller doesn't have it — we can look it up."
      },
      {
        "id": "lotSize",
        "label": "Lot Size (Acres)",
        "type": "text",
        "required": true,
        "placeholder": "e.g., .23",
        "description": "What size is the parcel?"
      },
      {
        "id": "livingSqft",
        "label": "Approximate Total Living Square Footage",
        "type": "number",
        "required": true
      }
    ]
  },
  {
    "order": 6,
    "id": "level-breakdown",
    "title": "Breakdown By Level",
    "intro": "We apologize that this section may be difficult via a mobile device.\n\nHowever, this is how the MLS distributes and formats your information. The more accurate this information, the more buyers you will reach.\n\n(If you don't have the approximate square feet per level, just leave blank and we can look it up for you. We do need the other information filled out accurately)\n\nEx: Basement + Main Level + Second Story = 3 Levels\nEx: Multi Level could be 3 or 4 depending on the basement.\n",
    "fields": [
      {
        "id": "levelCount",
        "label": "How Many Levels In The Property?",
        "type": "radio",
        "required": true,
        "options": [
          "1",
          "2",
          "3",
          "4",
          "5"
        ],
        "otherText": false
      },
      {
        "id": "q26-typea26",
        "label": "Basement / Lower Level Type",
        "type": "checkbox",
        "required": true,
        "options": [
          "Daylight",
          "Entrance",
          "Full",
          "Walkout",
          "Shelf",
          "Partial",
          "None / Crawlspace / Slab"
        ],
        "otherText": false
      },
      {
        "id": "basementFinished",
        "label": "Basement Finished",
        "type": "radio",
        "required": true,
        "options": [
          "Yes",
          "No",
          "Partial",
          "N/A"
        ],
        "otherText": false
      },
      {
        "id": "q117-2level117",
        "type": "matrix",
        "label": "Please add the corresponding information for each level. (Scroll right to see all info)",
        "columns": [
          {
            "id": "square-footage",
            "label": "Square Footage(+/-)",
            "type": "number"
          },
          {
            "id": "bedrooms",
            "label": "Bedrooms",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7"
            ]
          },
          {
            "id": "master-y-n",
            "label": "Master (Y/N)",
            "type": "checkbox"
          },
          {
            "id": "full-baths",
            "label": "Full Baths",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6"
            ]
          },
          {
            "id": "3-4-baths",
            "label": "3/4 Baths",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6"
            ]
          },
          {
            "id": "1-2-baths",
            "label": "1/2 Baths",
            "type": "select",
            "options": [
              "0",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6"
            ]
          },
          {
            "id": "living-fam-rm",
            "label": "Living/Fam Rm",
            "type": "checkbox"
          },
          {
            "id": "laundry",
            "label": "Laundry",
            "type": "checkbox"
          },
          {
            "id": "fireplace",
            "label": "Fireplace",
            "type": "checkbox"
          }
        ],
        "dynamic": {
          "rowCountFrom": "levelCount",
          "rowLabels": [
            "Main Level",
            "Basement"
          ]
        }
      }
    ]
  },
  {
    "order": 7,
    "id": "interior-systems",
    "title": "Interior Systems",
    "intro": null,
    "fields": [
      {
        "id": "q33-flooring",
        "type": "checkbox",
        "label": "Flooring",
        "required": true,
        "description": "Select all that apply, or choose None if unknown.",
        "options": [
          "None",
          "Bamboo",
          "Carpet",
          "Concrete",
          "Cork",
          "Hardwood",
          "Laminate",
          "Linoleum",
          "Marble",
          "Natural Stone",
          "Slate",
          "Tile",
          "Vinyl",
          "LVP / Vinyl Plank",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q34-typea34",
        "type": "checkbox",
        "label": "Interior Special Features",
        "required": false,
        "description": "Select any that apply, or leave blank if none.",
        "options": [
          "None",
          "Wet Bar",
          "Basement Apartment",
          "Master Bath",
          "Bath: Separate Tub/Shower",
          "Great Room",
          "Instant Hot Water",
          "Second Kitchen",
          "Mother In Law Apartment",
          "Double Ovens",
          "Gas Range",
          "Gas Oven",
          "Theater Room",
          "Vaulted Ceilings",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q27-typea27",
        "type": "checkbox",
        "label": "Accessibility",
        "required": true,
        "description": "Select all that apply, or choose None if not applicable.",
        "options": [
          "None",
          "32\" Wide Doorways",
          "36\" Wide Hallways",
          "Ceiling Lift System",
          "Elevator",
          "Fully Accessible",
          "Grab Bars",
          "Ground Level",
          "Porch Lift",
          "Ramp",
          "Roll-In Shower",
          "Single Level Living",
          "Stair Lift",
          "Wheelchair Access",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q41-window-coverings",
        "type": "checkbox",
        "label": "Window Coverings",
        "required": true,
        "description": "Select all that apply, or choose None if not applicable.",
        "options": [
          "Blinds",
          "Draperies",
          "Full",
          "None",
          "Partial",
          "Plantation Shutters",
          "Shades",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q42-amenities",
        "type": "checkbox",
        "label": "Amenities",
        "required": false,
        "description": "Select community or property amenities that apply, or leave blank if none.",
        "options": [
          "None",
          "Cable TV Available",
          "Cable TV Wired",
          "Clubhouse",
          "Electric Dryer Hookup",
          "Exercise Room",
          "Gas Dryer Hookup",
          "Gated Community",
          "Home Warranty",
          "Park / Playground",
          "Sauna / Steam Room",
          "Swimming Pool",
          "Tennis Court",
          "Workshop",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q31-airconditioning",
        "type": "checkbox",
        "label": "Air Conditioning",
        "required": true,
        "description": "Select all that apply, or choose None if not applicable.",
        "options": [
          "Central Air; Electric",
          "Central Air; Gas",
          "Evaporative Cooler Roof",
          "Evaporative Cooler Window",
          "None",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q96-hvac96",
        "type": "checkbox",
        "label": "Heating",
        "required": true,
        "description": "Select all that apply, or choose None if unknown.",
        "options": [
          "None",
          "Furnace / Forced Air",
          "Gas",
          "Heat Pump",
          "Baseboard",
          "Radiant",
          "Electric",
          "Propane",
          "Wood Burning",
          "Hot Water / Steam",
          "Solar",
          "Other"
        ],
        "otherText": true
      }
    ]
  },
  {
    "order": 8,
    "id": "exterior-parking",
    "title": "Exterior & Parking",
    "intro": null,
    "fields": [
      {
        "id": "q32-typea32",
        "type": "checkbox",
        "label": "Exterior",
        "required": true,
        "options": [
          "Aluminum",
          "Brick",
          "Cedar",
          "Cement Board",
          "Cinder Block",
          "Clapboard/Masonite",
          "Concrete",
          "Container",
          "Frame",
          "Glass",
          "Insulated Concrete Forms",
          "Log",
          "Metal",
          "Wood",
          "Stone",
          "Stucco",
          "Vinyl",
          "Shingles",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q29-typea29",
        "type": "checkbox",
        "label": "Exterior Special Features",
        "required": false,
        "description": "Select any that apply, or leave blank if none.",
        "options": [
          "None",
          "Balcony",
          "Barn",
          "Basement Entrance",
          "Bay Box Windows",
          "Deck: Covered",
          "Horse Property",
          "Out Buildings",
          "Outdoor Lighting",
          "Patio Covered",
          "Porch",
          "Skylights",
          "Walkout",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q30-typea30",
        "type": "checkbox",
        "label": "Parking",
        "required": true,
        "options": [
          "Garage",
          "Carport",
          "Attached",
          "Detached",
          "Extra Height",
          "Extra Length",
          "Extra Width",
          "2 Car Deep (Tandem)",
          "Heated",
          "RV Parking",
          "Workshop",
          "Underground",
          "Assigned Stall",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q208-garagecapacity",
        "type": "number",
        "label": "Garage Capacity",
        "status": "hidden-in-jotform",
        "min": 1,
        "max": 10,
        "default": 2
      },
      {
        "id": "q209-garagecapacity209",
        "type": "number",
        "label": "Carport Capacity",
        "status": "hidden-in-jotform",
        "min": 1,
        "max": 10,
        "default": 1
      },
      {
        "id": "q28-typea28",
        "type": "checkbox",
        "label": "Driveway",
        "required": true,
        "options": [
          "Concrete",
          "Asphalt",
          "Circular",
          "Common Drive",
          "Gravel",
          "Dirt",
          "Heated",
          "Other"
        ],
        "otherText": true
      }
    ]
  },
  {
    "order": 9,
    "id": "pool-roof-yard",
    "title": "Pool, Roof & Yard",
    "intro": null,
    "fields": [
      {
        "id": "q184-doesthe",
        "type": "radio",
        "label": "Does the property (including HOA) have a pool?",
        "required": true,
        "options": [
          "Yes",
          "No"
        ],
        "otherText": false
      },
      {
        "id": "q63-pooltype",
        "type": "checkbox",
        "label": "Pool Type / Features",
        "required": true,
        "status": "hidden-in-jotform",
        "options": [
          "Above Ground",
          "In Ground",
          "Concrete",
          "Fiberglass/Vinyl",
          "Heated",
          "With Spa/Hot Tub",
          "Powered Cover",
          "Fenced",
          "Indoor",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q37-typea37",
        "type": "checkbox",
        "label": "Roof",
        "required": true,
        "options": [
          "Asphalt Shingles",
          "Wood Shake",
          "Metal",
          "Aluminum",
          "Flat",
          "Fiberglass",
          "Composition",
          "Membrane",
          "PVC",
          "Rubber (EPDM)",
          "Stone",
          "Tar / Gravel",
          "Tile",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q36-typea36",
        "type": "checkbox",
        "label": "Yard / Landscaping",
        "required": true,
        "options": [
          "Full Landscaping",
          "Mature Trees",
          "Stream",
          "Xeriscaped",
          "Adjacent To Golf Course",
          "Cul-de-sac",
          "Corner Lot",
          "Sprinkler System",
          "Fenced",
          "Waterfront",
          "Wooded",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q43-lot-facts",
        "type": "checkbox",
        "label": "Lot Facts",
        "required": true,
        "options": [
          "Additional Land Available",
          "Adjacent to Golf Course",
          "Corner Lot",
          "Cul-de-sac",
          "Curb & Gutter",
          "Fenced, Full",
          "Fenced, Part",
          "Private",
          "Road, Paved",
          "Road, Unpaved",
          "Secluded Yard",
          "Sidewalks",
          "Terrain, Flat",
          "Terrain, Grad Slope",
          "Terrain, Hilly",
          "Terrain, Mountain",
          "View, Lake",
          "View, Mountain",
          "View, Valley",
          "Wooded",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q47-animals",
        "type": "radio",
        "label": "Animals / Pets",
        "required": true,
        "description": "WFRMLS allows one selection.",
        "options": [
          "None",
          "Pets < 20 Lbs.",
          "Pets 20 - 75 Lbs.",
          "Pets > 75 Lbs.",
          "Livestock",
          "Other"
        ],
        "otherText": true
      }
    ]
  },
  {
    "order": 10,
    "id": "utilities-zoning-terms",
    "title": "Utilities, Zoning & Terms",
    "intro": null,
    "fields": [
      {
        "id": "q39-typea39",
        "type": "checkbox",
        "label": "Storage",
        "required": true,
        "options": [
          "Basement",
          "Carport",
          "Garage",
          "Patio",
          "Shed",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q35-connectedutilities",
        "type": "checkbox",
        "label": "Connected Utilities",
        "required": true,
        "options": [
          "Natural Gas",
          "Power",
          "Sewer",
          "Septic",
          "Culinary Water Only",
          "Irrigantion Water",
          "Secondary Water",
          "Water Rights Owned",
          "Water Shares",
          "Well",
          "Spring",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q44-water",
        "type": "checkbox",
        "label": "Water",
        "required": true,
        "description": "Select all water sources that apply (WFRMLS separate from connected utilities).",
        "options": [
          "Culinary",
          "Irrigation",
          "Irrigation, Pressure",
          "Private",
          "Rights, Owned",
          "Rights, Rented",
          "Secondary",
          "Shares",
          "Spring",
          "Well",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q45-telecommunications",
        "type": "checkbox",
        "label": "Telecommunications",
        "required": true,
        "options": [
          "Broadband Cable",
          "DSL",
          "Ethernet, Wired",
          "Fiber Optics",
          "Multiple Phone Lines",
          "Wireless Broadband",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q46-environmental-certs",
        "type": "checkbox",
        "label": "Environmental Certifications",
        "options": [
          "None",
          "Built Green",
          "Energy Star",
          "Home Energy Rating",
          "LEED",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q38-zoning",
        "type": "checkbox",
        "label": "Zoning",
        "required": true,
        "options": [
          "Residential",
          "Multi Family",
          "Short Term Rental Allowed",
          "Commercial",
          "Agricultural",
          "Horse Property",
          "Industrial",
          "Other"
        ],
        "otherText": true
      },
      {
        "id": "q40-typea40",
        "type": "checkbox",
        "label": "Terms (acceptable terms of sale)",
        "required": true,
        "options": [
          "Cash",
          "Conventional Loan",
          "VA / FHA Loan",
          "Exchange",
          "Lease Option",
          "Seller Finance",
          "Other"
        ],
        "otherText": true
      }
    ]
  },
  {
    "order": 11,
    "id": "personal-property",
    "title": "Personal Property / Conveyances",
    "intro": null,
    "fields": [
      {
        "id": "q19-typea19",
        "label": "Personal Property / Conveyances",
        "type": "checkbox",
        "description": "Select all items included with the sale.",
        "options": [
          "Alarm System",
          "Basketball Standard",
          "Washer",
          "Dryer",
          "Dog Run",
          "Fireplace Equipment",
          "Fireplace Insert",
          "Freezer",
          "Gas Grill / BBQ",
          "Gazebo",
          "Hot Tub",
          "Humidifier",
          "Microwave",
          "Gym Equipment",
          "Playset",
          "Projector",
          "Range",
          "Refrigerator",
          "Satellite Equipment",
          "Storage Shed (s)",
          "Swing Set",
          "Trampoline",
          "Video Door Bell(s)",
          "Video / Alarm Cameras",
          "Water Softener",
          "Workbench",
          "Window Coverings",
          "Other"
        ],
        "otherText": true
      }
    ]
  },
  {
    "order": 12,
    "id": "buyer-showings",
    "title": "Buyer Showings",
    "intro": null,
    "fields": [
      {
        "id": "field-81",
        "type": "content",
        "content": "BUYER SHOWINGS\nPlease let us know if the property is owner occupied, tenant occupied or vacant and who is authorized to approve buyer showings with their contact information.\nShowing approvals can be made via text message & email. \nWe will deliver a secure electronic lock box and it will be placed on or around the front door area.  This box can ONLY be accessed by licensed agents once they have scheduled an appointment. \n"
      },
      {
        "id": "q191-propertyoccupancy",
        "type": "radio",
        "label": "Property Occupancy",
        "required": true,
        "options": [
          "Owner Occupied",
          "Tenant Occupied",
          "Vacant / Immediate Appt Approval"
        ],
        "otherText": false
      },
      {
        "id": "q192-howmany",
        "type": "radio",
        "label": "How Many Owners Can Approve Showings?",
        "status": "hidden-in-jotform",
        "options": [
          "One",
          "Two"
        ],
        "otherText": false
      },
      {
        "id": "q193-howmany193",
        "type": "radio",
        "label": "How Many Tenants Can Approve Showings?",
        "status": "hidden-in-jotform",
        "options": [
          "One",
          "Two"
        ],
        "otherText": false
      },
      {
        "id": "q194-ownershowing",
        "type": "fullname",
        "label": "Owner Showing Contact 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q195-phonenumber",
        "type": "phone",
        "label": "Owner Showing Phone 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q196-email",
        "type": "email",
        "label": "Owner Showing Email 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q197-ownershowing197",
        "type": "fullname",
        "label": "Owner Showing Contact 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q198-ownershowing198",
        "type": "phone",
        "label": "Owner Showing Phone 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q199-ownershowing199",
        "type": "email",
        "label": "Owner Showing Email 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q200-tenantshowing",
        "type": "fullname",
        "label": "Tenant Showing Contact 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q201-ownershowing201",
        "type": "phone",
        "label": "Tenant Showing Phone 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q202-tenantshowing202",
        "type": "email",
        "label": "Tenant Showing Email 1",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q203-tenantshowing203",
        "type": "fullname",
        "label": "Tenant Showing Contact 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q204-tenantshowing204",
        "type": "phone",
        "label": "Tenant Showing Phone 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q205-tenantshowing205",
        "type": "email",
        "label": "Tenant Showing Email 2",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q100-showinginstructions",
        "type": "textarea",
        "label": "Showing Instructions",
        "placeholder": "Please share any important access information and how to handle those items. (Pets, Alarms, Tenants, etc.)  Please be as detailed as possible."
      }
    ]
  },
  {
    "order": 13,
    "id": "title-company",
    "title": "Title Company",
    "intro": null,
    "fields": [
      {
        "id": "field-210",
        "type": "content",
        "content": "Title Company\nWould you like us to open your title work with Prime Title Co?\n(This will expedite the process and they will be notified upon listing)\n"
      },
      {
        "id": "q207-typea207",
        "type": "radio",
        "options": [
          "Yes",
          "No, I have someone else"
        ],
        "otherText": false
      },
      {
        "id": "q211-name211",
        "type": "fullname",
        "label": "Title Co Contact",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q212-typea212",
        "type": "text",
        "label": "Title Company Name",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q213-email213",
        "type": "email",
        "label": "Title Co Email",
        "status": "hidden-in-jotform"
      },
      {
        "id": "q214-phonenumber214",
        "type": "phone",
        "label": "Title Company Phone",
        "status": "hidden-in-jotform"
      }
    ]
  },
  {
    "order": 14,
    "id": "remarks",
    "title": "Remarks",
    "intro": null,
    "fields": [
      {
        "id": "q97-publicremarks",
        "type": "textarea",
        "label": "Public Remarks / House Description",
        "placeholder": "Please give a description of the home highlighting it's best features.  We may modify it with your approval prior to posting on the MLS."
      },
      {
        "id": "hoaRemarks",
        "type": "textarea",
        "label": "HOA Remarks",
        "status": "hidden-in-jotform",
        "placeholder": "Any HOA restrictions, fees, or rules buyers should know."
      },
      {
        "id": "exclusionsRemarks",
        "type": "textarea",
        "label": "Exclusions Remarks",
        "placeholder": "List any items explicitly excluded from the sale."
      },
      {
        "id": "q98-commentsto",
        "type": "textarea",
        "label": "Comments To Utah Digs",
        "placeholder": "These comments will only be seen by us.  Any special features, situations, concerns etc."
      }
    ]
  },
  {
    "order": 15,
    "id": "photos",
    "title": "Photos",
    "intro": null,
    "fields": [
      {
        "id": "field-218",
        "type": "content",
        "content": "Photos\nIf you have your own photos you can upload now. We recommend uploading later in your seller app/portal under \"manage your listing\" to avoid resetting this form if files are too large. We will need 2 exterior and 3 interior photos minimum to list on the MLS.\n** A professional photo tour is included with the Full Service Listing and will be scheduled upon receipt of your listing agreement and this form**\n"
      },
      {
        "id": "field-44",
        "label": "Property photos",
        "type": "file",
        "multiple": true
      }
    ]
  },
  {
    "order": 16,
    "id": "signature",
    "title": "Signature",
    "intro": null,
    "fields": [
      {
        "id": "field-217",
        "type": "content",
        "content": "The Undersigned represents and acknowledges that Undersigned is the owner of the real property described in this Listing Input Form (“Owner”). Owner acknowledges that Wasatch Front Regional Multiple Listing Service, Inc. (“WFRMLS”) maintains a multiple listing service database for brokers, agents, and the public (“MLS Compilation”) and consents to all of the information included in this Listing Input Form (“Listing Content”) being included in the MLS Compilation.\nOwner hereby grants WFRMLS a license to the Listing Content for the following purposes, among others: display of the Listing Content in the MLS Compilation, distribution and sublicensing of the Listing Content to third parties for display and use by third parties, display of the Listing Content on UtahRealEstate.com and any other WFRMLS owned websites, and any other lawful use. Owner hereby represents and warrants that Owner has all right, title, and interest in and to any copyright rights and other intellectual property rights associated with the Listing Content and that the Listing Content is correct and accurate. Owner agrees to indemnify and hold harmless WFRMLS against all damages, costs and liabilities, including reasonable attorney fees, arising from any claim that the Listing Content or any portion thereof infringes the rights of any third party.\n"
      },
      {
        "id": "q20-signature",
        "type": "signature",
        "label": "Primary Owner Signature",
        "required": true
      },
      {
        "id": "q23-signature23",
        "type": "signature",
        "label": "Secondary Owner Signature (If applicable)",
        "status": "hidden-in-jotform"
      }
    ]
  }
];

export const MLS_INPUT_STEP_COUNT = MLS_INPUT_STEPS.length;

export function getMlsInputStep(order: number): MlsInputStep | undefined {
  return MLS_INPUT_STEPS.find((s) => s.order === order);
}

export function getAllMlsFieldIds(): string[] {
  const ids: string[] = [];
  for (const step of MLS_INPUT_STEPS) {
    for (const field of step.fields) {
      if (field.type !== "content") ids.push(field.id);
    }
  }
  return ids;
}

export function getFieldById(fieldId: string): MlsInputField | undefined {
  for (const step of MLS_INPUT_STEPS) {
    const field = step.fields.find((f) => f.id === fieldId);
    if (field) return field;
  }
  return undefined;
}
