// AUTO-GENERATED by prototypes/jot-forms/mls-input/scripts/codegen.mjs — do not edit manually
import { z } from "zod";
import { MLS_INPUT_STEPS } from "./schema";
import { isFieldVisible } from "./conditions";

export const step1Schema = z.object({
    "ownerCount": z.enum(["One", "Two"] as const, { message: "Required" }),
});

export const step2Schema = z.object({
    "primaryOwnerName": z.object({ first: z.string().min(1, "First name is required"), last: z.string().min(1, "Last name is required") }),
    "primaryOwnerPhone": z.string().min(7, "Phone is required"),
    "primaryOwnerEmail": z.string().email("Valid email is required"),
    "secondaryOwnerName": z.object({ first: z.string().min(1, "First name is required"), last: z.string().min(1, "Last name is required") }),
    "secondaryOwnerPhone": z.string().min(7, "Phone is required"),
    "secondaryOwnerEmail": z.string().email("Valid email is required"),
});

export const step3Schema = z.object({
    "listingAddress": z.object({ street: z.string().min(1, "Street is required"), city: z.string().min(1, "City is required"), state: z.string().min(1, "State is required"), zip: z.string().min(1, "ZIP is required") }),
    "listingCounty": z.string().min(1, "Required"),
    "listingQuadrant": z.enum(["NW", "NE", "SW", "SE"] as const).optional(),
    "listingCoordinates": z.string().optional(),
    "nonStandardAddress": z.enum(["No", "Yes"] as const, { message: "Required" }),
    "directionsRemarks": z.string().min(1, "Required"),
    "ownerAddressSameAsListing": z.enum(["Yes", "No"] as const, { message: "Required" }),
    "ownerAddress": z.object({ street: z.string().min(1, "Street is required"), city: z.string().min(1, "City is required"), state: z.string().min(1, "State is required"), zip: z.string().min(1, "ZIP is required") }),
    "listingPrice": z.string().min(1, "Required"),
    "shortSale": z.enum(["Not Short Sale", "Price Subject to 3rd Party Approval", "Price Previously Approved by 3rd Party", "Offer Under 3rd Party Review"] as const, { message: "Required" }),
    "schools": z.record(z.string(), z.object({ "name": z.string().optional() }).partial()),
});

export const step4Schema = z.object({
    "hoa": z.enum(["Yes", "No"] as const, { message: "Required" }),
    "hoaFeeMonth": z.string().min(1, "Required"),
    "hoaContact": z.string().optional(),
    "hoaContactPhone": z.string().optional(),
    "shortTermRentals": z.enum(["Yes", "No", "Unknown"] as const).optional(),
    "solar": z.enum(["Yes", "No"] as const, { message: "Required" }),
});

export const step5Schema = z.object({
    "q11-propertytype": z.enum(["Single Family", "Condominium", "Mobile (w/o land)", "Recreational", "Townhouse", "Twin", "P.U.D."] as const, { message: "Required" }),
    "constructionStatus": z.enum(["Built/Standing", "Under Construction", "To Be Built"] as const, { message: "Required" }),
    "q51-styleof51": z.string().min(1, "Required"),
    "yearBuilt": z.string().min(1, "Required"),
    "effectiveYearBuilt": z.string().optional(),
    "taxParcelNumber": z.string().optional(),
    "lotSize": z.string().min(1, "Required"),
    "livingSqft": z.string().min(1, "Required"),
});

export const step6Schema = z.object({
    "levelCount": z.enum(["1", "2", "3", "4", "5"] as const, { message: "Required" }),
    "q26-typea26": z.array(z.string()).min(1, "Select at least one"),
    "basementFinished": z.enum(["Yes", "No", "Partial", "N/A"] as const, { message: "Required" }),
    "q117-2level117": z.record(z.string(), z.object({ "square-footage": z.string().optional(), "bedrooms": z.enum(["0", "1", "2", "3", "4", "5", "6", "7"] as const).optional(), "master-y-n": z.array(z.string()).optional(), "full-baths": z.enum(["0", "1", "2", "3", "4", "5", "6"] as const).optional(), "3-4-baths": z.enum(["0", "1", "2", "3", "4", "5", "6"] as const).optional(), "1-2-baths": z.enum(["0", "1", "2", "3", "4", "5", "6"] as const).optional(), "living-fam-rm": z.array(z.string()).optional(), "laundry": z.array(z.string()).optional(), "fireplace": z.array(z.string()).optional() }).partial()).optional(),
});

export const step7Schema = z.object({
    "q33-flooring": z.array(z.string()).min(1, "Select at least one"),
    "q34-typea34": z.array(z.string()).optional(),
    "q27-typea27": z.array(z.string()).min(1, "Select at least one"),
    "q41-window-coverings": z.array(z.string()).min(1, "Select at least one"),
    "q42-amenities": z.array(z.string()).optional(),
    "q31-airconditioning": z.array(z.string()).min(1, "Select at least one"),
    "q96-hvac96": z.array(z.string()).min(1, "Select at least one"),
});

export const step8Schema = z.object({
    "q32-typea32": z.array(z.string()).min(1, "Select at least one"),
    "q29-typea29": z.array(z.string()).optional(),
    "q30-typea30": z.array(z.string()).min(1, "Select at least one"),
    "q208-garagecapacity": z.string().optional(),
    "q209-garagecapacity209": z.string().optional(),
    "q28-typea28": z.array(z.string()).min(1, "Select at least one"),
});

export const step9Schema = z.object({
    "q184-doesthe": z.enum(["Yes", "No"] as const, { message: "Required" }),
    "q63-pooltype": z.array(z.string()).min(1, "Select at least one"),
    "q37-typea37": z.array(z.string()).min(1, "Select at least one"),
    "q36-typea36": z.array(z.string()).min(1, "Select at least one"),
    "q43-lot-facts": z.array(z.string()).min(1, "Select at least one"),
    "q47-animals": z.string().min(1, "Required"),
});

export const step10Schema = z.object({
    "q39-typea39": z.array(z.string()).min(1, "Select at least one"),
    "q35-connectedutilities": z.array(z.string()).min(1, "Select at least one"),
    "q44-water": z.array(z.string()).min(1, "Select at least one"),
    "q45-telecommunications": z.array(z.string()).min(1, "Select at least one"),
    "q46-environmental-certs": z.array(z.string()).optional(),
    "q38-zoning": z.array(z.string()).min(1, "Select at least one"),
    "q40-typea40": z.array(z.string()).min(1, "Select at least one"),
});

export const step11Schema = z.object({
    "q19-typea19": z.array(z.string()).optional(),
});

export const step12Schema = z.object({
    "q191-propertyoccupancy": z.enum(["Owner Occupied", "Tenant Occupied", "Vacant / Immediate Appt Approval"] as const, { message: "Required" }),
    "q192-howmany": z.enum(["One", "Two"] as const).optional(),
    "q193-howmany193": z.enum(["One", "Two"] as const).optional(),
    "q194-ownershowing": z.object({ first: z.string(), last: z.string() }).optional(),
    "q195-phonenumber": z.string().optional(),
    "q196-email": z.string().email().optional().or(z.literal("")),
    "q197-ownershowing197": z.object({ first: z.string(), last: z.string() }).optional(),
    "q198-ownershowing198": z.string().optional(),
    "q199-ownershowing199": z.string().email().optional().or(z.literal("")),
    "q200-tenantshowing": z.object({ first: z.string(), last: z.string() }).optional(),
    "q201-ownershowing201": z.string().optional(),
    "q202-tenantshowing202": z.string().email().optional().or(z.literal("")),
    "q203-tenantshowing203": z.object({ first: z.string(), last: z.string() }).optional(),
    "q204-tenantshowing204": z.string().optional(),
    "q205-tenantshowing205": z.string().email().optional().or(z.literal("")),
    "q100-showinginstructions": z.string().optional(),
});

export const step13Schema = z.object({
    "q207-typea207": z.enum(["Yes", "No, I have someone else"] as const).optional(),
    "q211-name211": z.object({ first: z.string(), last: z.string() }).optional(),
    "q212-typea212": z.string().optional(),
    "q213-email213": z.string().email().optional().or(z.literal("")),
    "q214-phonenumber214": z.string().optional(),
});

export const step14Schema = z.object({
    "q97-publicremarks": z.string().optional(),
    "hoaRemarks": z.string().optional(),
    "exclusionsRemarks": z.string().optional(),
    "q98-commentsto": z.string().optional(),
});

export const step15Schema = z.object({
    "field-44": z.array(z.object({ name: z.string(), url: z.string().url() })).optional(),
});

export const step16Schema = z.object({
    "q20-signature": z.string().url("Signature is required"),
    "q23-signature23": z.string().url().optional().or(z.literal("")),
});

export const fullMlsInputSchema = z.object({
  "ownerCount": z.enum(["One", "Two"] as const, { message: "Required" }),
  "primaryOwnerName": z.object({ first: z.string().min(1, "First name is required"), last: z.string().min(1, "Last name is required") }),
  "primaryOwnerPhone": z.string().min(7, "Phone is required"),
  "primaryOwnerEmail": z.string().email("Valid email is required"),
  "secondaryOwnerName": z.object({ first: z.string().min(1, "First name is required"), last: z.string().min(1, "Last name is required") }),
  "secondaryOwnerPhone": z.string().min(7, "Phone is required"),
  "secondaryOwnerEmail": z.string().email("Valid email is required"),
  "listingAddress": z.object({ street: z.string().min(1, "Street is required"), city: z.string().min(1, "City is required"), state: z.string().min(1, "State is required"), zip: z.string().min(1, "ZIP is required") }),
  "listingCounty": z.string().min(1, "Required"),
  "listingQuadrant": z.enum(["NW", "NE", "SW", "SE"] as const).optional(),
  "listingCoordinates": z.string().optional(),
  "nonStandardAddress": z.enum(["No", "Yes"] as const, { message: "Required" }),
  "directionsRemarks": z.string().min(1, "Required"),
  "ownerAddressSameAsListing": z.enum(["Yes", "No"] as const, { message: "Required" }),
  "ownerAddress": z.object({ street: z.string().min(1, "Street is required"), city: z.string().min(1, "City is required"), state: z.string().min(1, "State is required"), zip: z.string().min(1, "ZIP is required") }),
  "listingPrice": z.string().min(1, "Required"),
  "shortSale": z.enum(["Not Short Sale", "Price Subject to 3rd Party Approval", "Price Previously Approved by 3rd Party", "Offer Under 3rd Party Review"] as const, { message: "Required" }),
  "schools": z.record(z.string(), z.object({ "name": z.string().optional() }).partial()),
  "hoa": z.enum(["Yes", "No"] as const, { message: "Required" }),
  "hoaFeeMonth": z.string().min(1, "Required"),
  "hoaContact": z.string().optional(),
  "hoaContactPhone": z.string().optional(),
  "shortTermRentals": z.enum(["Yes", "No", "Unknown"] as const).optional(),
  "solar": z.enum(["Yes", "No"] as const, { message: "Required" }),
  "q11-propertytype": z.enum(["Single Family", "Condominium", "Mobile (w/o land)", "Recreational", "Townhouse", "Twin", "P.U.D."] as const, { message: "Required" }),
  "constructionStatus": z.enum(["Built/Standing", "Under Construction", "To Be Built"] as const, { message: "Required" }),
  "q51-styleof51": z.string().min(1, "Required"),
  "yearBuilt": z.string().min(1, "Required"),
  "effectiveYearBuilt": z.string().optional(),
  "taxParcelNumber": z.string().optional(),
  "lotSize": z.string().min(1, "Required"),
  "livingSqft": z.string().min(1, "Required"),
  "levelCount": z.enum(["1", "2", "3", "4", "5"] as const, { message: "Required" }),
  "q26-typea26": z.array(z.string()).min(1, "Select at least one"),
  "basementFinished": z.enum(["Yes", "No", "Partial", "N/A"] as const, { message: "Required" }),
  "q117-2level117": z.record(z.string(), z.object({ "square-footage": z.string().optional(), "bedrooms": z.enum(["0", "1", "2", "3", "4", "5", "6", "7"] as const).optional(), "master-y-n": z.array(z.string()).optional(), "full-baths": z.enum(["0", "1", "2", "3", "4", "5", "6"] as const).optional(), "3-4-baths": z.enum(["0", "1", "2", "3", "4", "5", "6"] as const).optional(), "1-2-baths": z.enum(["0", "1", "2", "3", "4", "5", "6"] as const).optional(), "living-fam-rm": z.array(z.string()).optional(), "laundry": z.array(z.string()).optional(), "fireplace": z.array(z.string()).optional() }).partial()).optional(),
  "q33-flooring": z.array(z.string()).min(1, "Select at least one"),
  "q34-typea34": z.array(z.string()).optional(),
  "q27-typea27": z.array(z.string()).min(1, "Select at least one"),
  "q41-window-coverings": z.array(z.string()).min(1, "Select at least one"),
  "q42-amenities": z.array(z.string()).optional(),
  "q31-airconditioning": z.array(z.string()).min(1, "Select at least one"),
  "q96-hvac96": z.array(z.string()).min(1, "Select at least one"),
  "q32-typea32": z.array(z.string()).min(1, "Select at least one"),
  "q29-typea29": z.array(z.string()).optional(),
  "q30-typea30": z.array(z.string()).min(1, "Select at least one"),
  "q208-garagecapacity": z.string().optional(),
  "q209-garagecapacity209": z.string().optional(),
  "q28-typea28": z.array(z.string()).min(1, "Select at least one"),
  "q184-doesthe": z.enum(["Yes", "No"] as const, { message: "Required" }),
  "q63-pooltype": z.array(z.string()).min(1, "Select at least one"),
  "q37-typea37": z.array(z.string()).min(1, "Select at least one"),
  "q36-typea36": z.array(z.string()).min(1, "Select at least one"),
  "q43-lot-facts": z.array(z.string()).min(1, "Select at least one"),
  "q47-animals": z.string().min(1, "Required"),
  "q39-typea39": z.array(z.string()).min(1, "Select at least one"),
  "q35-connectedutilities": z.array(z.string()).min(1, "Select at least one"),
  "q44-water": z.array(z.string()).min(1, "Select at least one"),
  "q45-telecommunications": z.array(z.string()).min(1, "Select at least one"),
  "q46-environmental-certs": z.array(z.string()).optional(),
  "q38-zoning": z.array(z.string()).min(1, "Select at least one"),
  "q40-typea40": z.array(z.string()).min(1, "Select at least one"),
  "q19-typea19": z.array(z.string()).optional(),
  "q191-propertyoccupancy": z.enum(["Owner Occupied", "Tenant Occupied", "Vacant / Immediate Appt Approval"] as const, { message: "Required" }),
  "q192-howmany": z.enum(["One", "Two"] as const).optional(),
  "q193-howmany193": z.enum(["One", "Two"] as const).optional(),
  "q194-ownershowing": z.object({ first: z.string(), last: z.string() }).optional(),
  "q195-phonenumber": z.string().optional(),
  "q196-email": z.string().email().optional().or(z.literal("")),
  "q197-ownershowing197": z.object({ first: z.string(), last: z.string() }).optional(),
  "q198-ownershowing198": z.string().optional(),
  "q199-ownershowing199": z.string().email().optional().or(z.literal("")),
  "q200-tenantshowing": z.object({ first: z.string(), last: z.string() }).optional(),
  "q201-ownershowing201": z.string().optional(),
  "q202-tenantshowing202": z.string().email().optional().or(z.literal("")),
  "q203-tenantshowing203": z.object({ first: z.string(), last: z.string() }).optional(),
  "q204-tenantshowing204": z.string().optional(),
  "q205-tenantshowing205": z.string().email().optional().or(z.literal("")),
  "q100-showinginstructions": z.string().optional(),
  "q207-typea207": z.enum(["Yes", "No, I have someone else"] as const).optional(),
  "q211-name211": z.object({ first: z.string(), last: z.string() }).optional(),
  "q212-typea212": z.string().optional(),
  "q213-email213": z.string().email().optional().or(z.literal("")),
  "q214-phonenumber214": z.string().optional(),
  "q97-publicremarks": z.string().optional(),
  "hoaRemarks": z.string().optional(),
  "exclusionsRemarks": z.string().optional(),
  "q98-commentsto": z.string().optional(),
  "field-44": z.array(z.object({ name: z.string(), url: z.string().url() })).optional(),
  "q20-signature": z.string().url("Signature is required"),
  "q23-signature23": z.string().url().optional().or(z.literal("")),
  inquiryId: z.string().optional(),
  photos: z.array(z.object({ name: z.string(), url: z.string().url() })).optional(),
});

export type FullMlsInputValues = z.infer<typeof fullMlsInputSchema>;

const stepSchemas = [
  step1Schema,
  step2Schema,
  step3Schema,
  step4Schema,
  step5Schema,
  step6Schema,
  step7Schema,
  step8Schema,
  step9Schema,
  step10Schema,
  step11Schema,
  step12Schema,
  step13Schema,
  step14Schema,
  step15Schema,
  step16Schema
] as const;

export function validateMlsInputStep(
  stepOrder: number,
  values: Record<string, unknown>,
): { success: true } | { success: false; fieldErrors: Record<string, string> } {
  const schema = stepSchemas[stepOrder - 1];
  if (!schema) return { success: true };

  const visibleShape: Record<string, z.ZodTypeAny> = {};
  const step = MLS_INPUT_STEPS[stepOrder - 1];
  if (!step) return { success: true };

  for (const field of step.fields) {
    if (field.type === "content") continue;
    if (!isFieldVisible(field.id, values)) continue;
    const fieldSchema = (schema.shape as Record<string, z.ZodTypeAny>)[field.id];
    if (fieldSchema) visibleShape[field.id] = fieldSchema;
  }

  const result = z.object(visibleShape).safeParse(values);
  if (result.success) return { success: true };

  const fieldErrors: Record<string, string> = {};
  for (const issue of result.error.issues) {
    const key = issue.path[0];
    if (typeof key === "string" && !fieldErrors[key]) {
      fieldErrors[key] = issue.message;
    }
  }
  return { success: false, fieldErrors };
}

export function validateFullMlsInput(
  values: Record<string, unknown>,
): { success: true; data: FullMlsInputValues } | { success: false; fieldErrors: Record<string, string> } {
  const visibleShape: Record<string, z.ZodTypeAny> = {};
  for (const [key, schema] of Object.entries(fullMlsInputSchema.shape)) {
    if (key === "inquiryId" || key === "photos") {
      visibleShape[key] = schema;
      continue;
    }
    if (isFieldVisible(key, values)) {
      visibleShape[key] = schema;
    }
  }

  const result = z.object(visibleShape).safeParse(values);
  if (result.success) return { success: true, data: result.data as FullMlsInputValues };

  const fieldErrors: Record<string, string> = {};
  for (const issue of result.error.issues) {
    const key = issue.path[0];
    if (typeof key === "string" && !fieldErrors[key]) {
      fieldErrors[key] = issue.message;
    }
  }
  return { success: false, fieldErrors };
}
